### ISSUE TITLE
uploaded zero-length blob to path

### ISSUE THREAD

**Issue by SvenDummel** [Azure/azure-storage-fuse#260] opened 2019-03-22 10:54 UTC
### Which version of the blobfuse was used?
blobfuse version 1.0.2

### Which OS (please include version) are you using?
Red Hat Enterprise Linux Server 7.6

### What problem was encountered?
Our application stores files  in a folder structure like

/mnt/blob/blob01/0ff0/005056b5e2f21ee9939046b541f32af9

here we have 2 files
one name with foldername and a .prob extension and another file called data
files:
005056b5e2f21ee9939046b541f32af9.prop
data

as long as the --file-cache-timeout-in-seconds is still running --> the *.prob file has a content

means the file exists on the blobstore as well as on the cache folder with the same content. As soon as the cache time is over the folder and files on the cache folder are deleted. On the blob store itself the size of the *.prob file is set to zero and the content of the file is gone. But the file still exists.

In the syslog you can see the following:
Mar 22 10:29:04 VMname01 blobfuse[16112]: Successfully uploaded zero-length directory marker for path /0e36 to blob 0e36.
Mar 22 10:29:05 VMname01 blobfuse[16112]: Successfully uploaded zero-length directory marker for path /0e36/SapCS.extensionArea to blob 0e36/SapCS.extensionArea.
Mar 22 10:29:05 VMname01 blobfuse[16112]: Successfully uploaded zero-length directory marker for path /0e36/005056b5e2f21ee99391aa1a5a250baa to blob 0e36/005056b5e2f21ee99391aa1a5a250baa.
Mar 22 10:29:05 VMname01 blobfuse[16112]: Successfully created file /0e36/005056b5e2f21ee99391aa1a5a250baa/005056b5e2f21ee99391aa1a5a250baa.prop in file cache.
Mar 22 10:29:05 VMname01 blobfuse[16112]: Successfully created file /0e36/005056b5e2f21ee99391aa1a5a250baa/data in file cache.
Mar 22 10:29:05 VMname01 blobfuse[16112]: Successfully uploaded file /0e36/005056b5e2f21ee99391aa1a5a250baa/data to blob 0e36/005056b5e2f21ee99391aa1a5a250baa/data.
Mar 22 10:29:05 VMname01 blobfuse[16112]: Successfully uploaded zero-length blob to path 0e36/005056b5e2f21ee99391aa1a5a250baa/005056b5e2f21ee99391aa1a5a250baa.prop from azs_truncate.
Mar 22 10:29:05 VMname01 blobfuse[16112]: Successfully uploaded file /0e36/005056b5e2f21ee99391aa1a5a250baa/005056b5e2f21ee99391aa1a5a250baa.prop to blob 0e36/005056b5e2f21ee99391aa1a5a250baa/005056b5e2f21ee99391aa1a5a250baa.prop.

### If relevant, please share your mount command.
blobfuse /mnt/blob/blob01 --tmp-path=/mnt/resource/blobfusetemp01 -o attr_timeout=20 -o entry_timeout=20 -o negative_timeout=120 -o allow_other --config-file=/opt/blob_config/.cred_10y --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=60 -o uid=1001 -o gid=994 -o sync_read

**Comment by seguler** [comment] 2019-03-28 03:22
Based on the logs, your application is calling truncate function on the file. Could you verify your application on a local filesystem first ?

**Comment by SvenDummel** [comment] 2019-03-29 06:27
Hi,
on the local filesystem everything works as expected. As log as the cache is is valid everything is ok. If I reduce the cache time to 0 the file on the blob is empty right away. There is a folder with the same name as the *.prop file.
any ideas?

**Comment by amnguye** [comment] 2019-10-07 23:40
This is a very weird bug. I've tried reproducing the issue, but no luck. I know that we create another blob to represent the directory however, why truncate is being called is very odd.

I will mark this as a bug for now, and look into it when we can due to the bug not being able to reproduce.

**Comment by abdulmbajwa** [comment] 2019-12-27 12:33
I am facing this same exact issue. This issue shows up after blobfuse is running for some time (12-24hrs). Blobfuse keeps the file reference and can be seen using lsof command.

**Comment by abdulmbajwa** [comment] 2020-01-09 11:42
Also, I have found one more thing is that when you "lsof" you can see blobfuse keeping files open in process and files don't get deleted automatically when cache timeout.

**Comment by vibhansa-msft** [comment] 2020-07-01 11:41
Can you try the same test case with the latest version. Also in the syslog that were shared earlier I see 'azs_truncate' which means a truncate call was received from the file system for the .prop file, which will clear off its contents.
-----
Mar 22 10:29:05 VMname01 blobfuse[16112]: Successfully uploaded zero-length blob to path 0e36/005056b5e2f21ee99391aa1a5a250baa/005056b5e2f21ee99391aa1a5a250baa.prop from azs_truncate
-----

**Comment by vibhansa-msft** [comment] 2020-09-01 16:52
Closing the issue as there have been no updates on this. Kindly reopen if the issue persists.

**Closed by vibhansa-msft** 2020-09-01 16:52 UTC
Labels: bug, triaged
