### ISSUE TITLE
Can we mount it with SAS token granted at folder level only?

### ISSUE THREAD

**Issue by enjgaa** [Azure/azure-storage-fuse#781] opened 2022-05-04 05:21 UTC
### Which version of the blobfuse was used?
blobfuse 1.4.3

### Which OS (please include version) are you using?
Ubuntu 20.04

### What problem was encountered?
When we give folder level access, we are not able to mount azure storage using blobfuse with SAS token.

### Have you found a mitigation/solution?
When we change the permission to container level, we were able to mount azure storage using blobfuse.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Unable to start blobfuse. Failed to connect to the storage container. There might be something wrong about storage config. please double check the storage account name, account key/sas token/OAuth access token and container name. errno=403

### If relevant, please share your mount command.
blobfuse /mnt/blobstorage --tmp-path=/mnt.blobfusetmp --config-file=/home/user1/.test_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o nonempty --pre-mount-validate=true

**Comment by gapra-msft** [comment] 2022-05-09 17:31
Hi @enjgaa 

This is by design. Blobfuse mounts at the container level so it needs permission to list the container. A directory level SAS will not give us permission to list the container. At minimum you would need to pass in container level SAS.

**Comment by gapra-msft** [comment] 2022-05-09 17:32
@tasherif-msft, @vibhansa-msft, @souravgupta-msft for the future, do you think we could take up a feature where we detect something like this (usage of a non container level/ account level sas) and throw early?

**Comment by tasherif-msft** [comment] 2022-05-11 18:06
@gapra-msft yes, I think this should def throw early in V2

**Comment by vibhansa-msft** [comment] 2022-05-16 06:31
@tasherif-msft : add a backlog item for the same in V2, closing this issue here, as we are not taking any feature request for v1 anymore.

**Closed by vibhansa-msft** 2022-05-16 06:31 UTC
Labels: enhancement, triaged
