### ISSUE TITLE
Option `--foreground=true` in mount all halts after the first mount

### ISSUE THREAD

**Issue by BMMevius** [Azure/azure-storage-fuse#981] opened 2022-11-16 15:09 UTC
### Which version of blobfuse was used?
Main (6165f412b77935ee59522a52b3e1dce1e9a3765c)

### Which OS distribution and version are you using?
Arch linux 6.0.8-arch1-1 (64bit)

### If relevant, please share your mount command.
```
blobfuse2 mount all /run/media/azure --allow-other --foreground=true --tmp-path=/tmp/blobfuse2 --log-level=LOG_DEBUG --config-file=config-file.yml
```

### What was the issue encountered?
Only mounts the first mount if `--foreground=true` is given.
Expected was that the main process stays in the foreground but all mounts are mounted.
Prevents from use in a start up service where the `ExecStop` option is `blobfuse2 unmount all`.

### Have you found a mitigation/solution?
-

### Please share logs if available.
```
Started A virtual file system adapter for Azure Blob storage..
LOG_CRIT [mount_all.go (155)]: Starting Blobfuse2 Mount All: 2.0.0-preview.5
LOG_CRIT [mount_all.go (156)]: Logging level set to : LOG_DEBUG
LOG_TRACE [azstorage.go (83)]: AzStorage::Configure : azstorage
LOG_TRACE [config.go (270)]: ParseAndValidateConfig : Parsing config
LOG_INFO [config.go (372)]: ParseAndValidateConfig : using the following proxy address from the config file:
LOG_INFO [config.go (376)]: ParseAndValidateConfig : sdk logging from the config file: false
LOG_TRACE [config.go (479)]: ParseAndReadDynamicConfig : Reparsing config
LOG_DEBUG [config.go (383)]: ParseAndValidateConfig : Getting auth type
LOG_INFO [config.go (467)]: ParseAndValidateConfig : Account: storage, Container: , AccountType: BLOCK, Auth: KEY, Prefix: , Endpoint: https://storage.blob.core.windows.net/, ListBlock: 0, MD5 : false false, Virtual Directory: true
LOG_INFO [config.go (471)]: ParseAndValidateConfig : Retry Config: Retry count 5, Max Timeout 900, BackOff Time 4, Max Delay 60
LOG_TRACE [block_blob.go (173)]: BlockBlob::SetupPipeline : Setting up
LOG_TRACE [block_blob.go (135)]: BlockBlob::getCredential : Getting credential
LOG_DEBUG [azauth.go (79)]: azAuth::getAzAuth : Account: storage, AccountType: BLOCK, Protocol: https, Endpoint: https://storage.blob.core.windows.net/
LOG_TRACE [block_blob.go (260)]: BlockBlob::SetPrefixPath : path
LOG_TRACE [block_blob.go (209)]: BlockBlob::TestPipeline : Validating
LOG_TRACE [azstorage.go (164)]: AzStorage::Start : Starting component azstorage
LOG_TRACE [block_blob.go (238)]: BlockBlob::ListContainers : Listing containers
LOG_TRACE [azstorage.go (177)]: AzStorage::Stop : Stopping component azstorage
Mounting container : container1 to path  /run/media/azure/container1
LOG_CRIT [mount.go (364)]: Starting Blobfuse2 Mount : 2.0.0-preview.5 on [Arch Linux]
LOG_CRIT [mount.go (365)]: Logging level set to : LOG_DEBUG
LOG_TRACE [libfuse.go (220)]: Libfuse::Configure : libfuse
LOG_INFO [libfuse.go (260)]: Libfuse::Configure : read-only false, allow-other true, default-perm 511, entry-timeout 120, attr-time 120, negative-timeout 120, ignore-open-flags: false, nonempty false
LOG_TRACE [stream.go (100)]: Stream::Configure : stream
LOG_INFO [read_write.go (58)]: ReadWriteCache::Configure : Streamonly set to true
LOG_INFO [stream.go (132)]: Stream::Configure : Buffer size 0, Block size 0, Handle limit 0
LOG_TRACE [attr_cache.go (121)]: AttrCache::Configure : attr_cache
LOG_INFO [attr_cache.go (145)]: AttrCache::Configure : cache-timeout 120, symlink false, cache-on-list true
LOG_TRACE [azstorage.go (83)]: AzStorage::Configure : azstorage
LOG_TRACE [config.go (270)]: ParseAndValidateConfig : Parsing config
LOG_INFO [config.go (372)]: ParseAndValidateConfig : using the following proxy address from the config file:
LOG_INFO [config.go (376)]: ParseAndValidateConfig : sdk logging from the config file: false
LOG_TRACE [config.go (479)]: ParseAndReadDynamicConfig : Reparsing config
LOG_DEBUG [config.go (383)]: ParseAndValidateConfig : Getting auth type
LOG_INFO [config.go (467)]: ParseAndValidateConfig : Account: storage, Container: container1, AccountType: BLOCK, Auth: KEY, Prefix: , Endpoint: https://storage.blob.core.windows.net/, ListBlock: 0, MD5 : false false, Virtual Directory: true
LOG_INFO [config.go (471)]: ParseAndValidateConfig : Retry Config: Retry count 5, Max Timeout 900, BackOff Time 4, Max Delay 60
LOG_TRACE [block_blob.go (173)]: BlockBlob::SetupPipeline : Setting up
LOG_TRACE [block_blob.go (135)]: BlockBlob::getCredential : Getting credential
LOG_DEBUG [azauth.go (79)]: azAuth::getAzAuth : Account: storage, AccountType: BLOCK, Protocol: https, Endpoint: https://storage.blob.core.windows.net/
LOG_TRACE [block_blob.go (260)]: BlockBlob::SetPrefixPath : path
LOG_TRACE [block_blob.go (209)]: BlockBlob::TestPipeline : Validating
LOG_INFO [mount.go (372)]: mount: Mounting blobfuse2 on /run/media/azure/container1
LOG_DEBUG [mount.go (418)]: mount: foreground enabled
LOG_DEBUG [mount.go (456)]: Mount::runPipeline : blobfuse2 pid = 9615, transfer pipe = /tmp/transferPipe_9615, polling pipe = /tmp/pollPipe_9615
LOG_TRACE [azstorage.go (164)]: AzStorage::Start : Starting component azstorage
LOG_TRACE [attr_cache.go (103)]: AttrCache::Start : Starting component attr_cache
LOG_TRACE [stream.go (95)]: Starting component : stream
LOG_TRACE [libfuse.go (136)]: Libfuse::Start : Starting component libfuse
LOG_TRACE [libfuse_handler.go (116)]: Libfuse::initFuse : Initializing FUSE3
LOG_TRACE [libfuse_handler.go (159)]: Libfuse::initFuse : Registering fuse callbacks
LOG_TRACE [libfuse_handler.go (163)]: Libfuse::initFuse : Populating fuse arguments
LOG_TRACE [libfuse_handler.go (187)]: Libfuse::populateFuseArgs
LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : blobfuse2
LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : /run/media/azure/container1
LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : -o
LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : entry_timeout=120,attr_timeout=120,negative_timeout=120,allow_other
LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : -f
LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : -ofsname=blobfuse2
LOG_DEBUG [libfuse_handler.go (224)]: Libfuse::populateFuseArgs : opts : -okernel_cache
LOG_INFO [libfuse_handler.go (175)]: Libfuse::initFuse : Mounting with fuse3 library
LOG_TRACE [libfuse_handler.go (244)]: Libfuse::libfuse_init : init
LOG_INFO [libfuse_handler.go (247)]: Libfuse::libfuse_init : Kernel Caps : 60817371
LOG_INFO [libfuse_handler.go (254)]: Libfuse::libfuse_init : Enable Capability : FUSE_CAP_PARALLEL_DIROPS
LOG_INFO [libfuse_handler.go (260)]: Libfuse::libfuse_init : Enable Capability : FUSE_CAP_AUTO_INVAL_DATA
LOG_INFO [libfuse_handler.go (267)]: Libfuse::libfuse_init : Enable Capability : FUSE_CAP_READDIRPLUS
LOG_INFO [libfuse_handler.go (273)]: Libfuse::libfuse_init : Enable Capability : FUSE_CAP_ASYNC_READ
LOG_INFO [libfuse_handler.go (279)]: Libfuse::libfuse_init : Enable Capability : FUSE_CAP_SPLICE_WRITE
LOG_INFO [libfuse_handler.go (291)]: Libfuse::libfuse_init : Enable Capability : FUSE_CAP_WRITEBACK_CACHE
```

**Comment by vibhansa-msft** [comment] 2022-11-16 15:50
As per current design whatever cli parameters are given to mount all are passed down to individual mounts as well. As you have given --foreground flag on mount all, it goes to mount, and first mount is done in foreground as well. This is the reason it hung up. It's not expected to run mount all with foreground.

**Comment by vibhansa-msft** [comment] 2022-11-16 15:53
Can you share little more details on how you wish to use this mount all option?

**Comment by BMMevius** [comment] 2022-11-16 20:18
I want to mount all storage containers at start up using a service. Without passing `--foreground` the service will exit after mounting all containers. In `ExecStop`, I have put the `unmount all` command. So this is executed as soon as the containers are mounted, unmounting all my containers again.

**Comment by vibhansa-msft** [comment] 2022-11-17 07:08
'Mount all' command is always in foreground. It basically iterates through your list of containers and fires one mount command implicitly for each of them. If you have 10 containers, you will see 10 mount points created and 10 instances of blobfuse running. Once mount all is done with executing this command it will just come out and complete so you will get the shell back. If you were calling unmount on exit, then immediately you will hit that. My guess is there is little misunderstanding here on how mount all works.

**Comment by BMMevius** [comment] 2022-11-17 08:35
I see how it works, but it would be nice to be able to use it in a service, without needing to create a service for each container.

**Comment by vibhansa-msft** [comment] 2022-11-21 04:39
Service needs to keep running in background for certain task. Mount-all is all about just forking multiple mounts. So even if we make that change, I still do not understand on what status/task it needs to wait? blobfuse2 binary mounts a container and waits until unmount command is triggered. Mount-all just forks all mount which then individually wait for their respective unmount. Mount-all cannot wait on anything. So, it still does not make sense to me on how to convert this to a service.
In case you have specific case, you can instead write a script that executes mount-all and then wait until all are unmounted. From your service just run this script.

**Comment by vibhansa-msft** [comment] 2022-11-23 09:23
We have added this item to our backlog. Will evaluate internally and see if this fits to common needs or not. Closing this here as it's not a bug.

**Closed by vibhansa-msft** 2022-11-23 09:23 UTC
Labels: enhancement, V2
