### ISSUE TITLE
BlobFuse Not working in RHEL 8.2

### ISSUE THREAD

**Issue by GunaGopal** [Azure/azure-storage-fuse#803] opened 2022-06-01 06:42 UTC
### Which version of the blobfuse was used?
Blobfuse version : 1.4.3

### Which OS (please include version) are you using?
RHEL 8.2

### What problem was encountered?
Blobfuse is not working, when I'm executing the below command it got hung and it is not showing any command output.

 blobfuse datafiles --tmp-path=/opt/data/softwares/blobfuse/temp  --config-file=/opt/data/softwares/blobfuse/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other --log-level=LOG_DEBUG

### Have you found a mitigation/solution?
Earlier we were using blob fuse version 1.4.1 then upgraded to 1.4.3 even after update it is not working

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

Below are the logs:

Jun  1 06:23:04 usa**** blobfuse[930995]: Using syscall to detect directory is already mounted or not
Jun  1 06:23:04 usa**** blobfuse[930995]: Setting logging level to : LOG_DEBUG
Jun  1 06:23:04 usa**** blobfuse[930995]: Disk Thresholds : 90 - 80, Cache Eviction : 1000-0, List Cancel time : 0 Retry Policy (0, 60.000000, 1.200000), Background Download 0, Evict on sync 0
Jun  1 06:23:04 usa**** blobfuse[930995]: Blobfuse version : 1.4.3
Jun  1 06:23:04 usa**** blobfuse[930995]: release is 4.180000, Kernel version is 4.18.0-193.14.3.el8_2.x86_64
Jun  1 06:23:04 usa**** blobfuse[930995]: CURL Version is 7.61.1
Jun  1 06:23:04 usa**** blobfuse[930995]: ** Delaying tls init to post fork for older libcurl version
Jun  1 06:23:04 usa**** blobfuse[930995]: ** Delaying authentication to post fork for older curl versions

### If relevant, please share your mount command.

 blobfuse datafiles --tmp-path=/opt/data/softwares/blobfuse/temp  --config-file=/opt/data/softwares/blobfuse/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other --log-level=LOG_DEBUG

**Comment by GunaGopal** [comment] 2022-06-01 10:07
Enabled rsyslog as well, below are the details:

tail -100f blobfuse.log
Jun  1 10:02:28 usa******** blobfuse[1027432]: Using syscall to detect directory is already mounted or not
Jun  1 10:02:28 usa******** blobfuse[1027432]: Account name found
Jun  1 10:02:28 usa******** blobfuse[1027432]: Account Key found
Jun  1 10:02:28 usa******** blobfuse[1027432]: Container name found
Jun  1 10:02:28 usa******** blobfuse[1027432]: Setting logging level to : LOG_DEBUG
Jun  1 10:02:28 usa******** blobfuse[1027432]: Disk Thresholds : 90 - 80, Cache Eviction : 1000-0, List Cancel time : 0 Retry Policy (0, 60.000000, 1.200000), Background Download 0, Evict on sync 0
Jun  1 10:02:28 usa******** blobfuse[1027432]: Blobfuse version : 1.4.3
Jun  1 10:02:28 usa******** blobfuse[1027432]: release is 4.180000, Kernel version is 4.18.0-193.14.3.el8_2.x86_64
Jun  1 10:02:28 usa******** blobfuse[1027432]: CURL Version is 7.61.1
Jun  1 10:02:28 usa******** blobfuse[1027432]: ** Delaying tls init to post fork for older libcurl version
Jun  1 10:02:28 usa******** blobfuse[1027432]: Function ensure_files_directory_exists_in_cache, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /opt.
Jun  1 10:02:28 usa******** blobfuse[1027432]: Function ensure_files_directory_exists_in_cache, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /opt/data.
Jun  1 10:02:28 usa******** blobfuse[1027432]: Function ensure_files_directory_exists_in_cache, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /opt/data/softwares.
Jun  1 10:02:28 usa******** blobfuse[1027432]: Function ensure_files_directory_exists_in_cache, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /opt/data/softwares/blobfuse.
Jun  1 10:02:28 usa******** blobfuse[1027432]: Function ensure_files_directory_exists_in_cache, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /opt/data/softwares/blobfuse/temp.
Jun  1 10:02:28 usa******** blobfuse[1027432]: Function ensure_files_directory_exists_in_cache, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /opt/data/softwares/blobfuse/temp/root.
Jun  1 10:02:28 usa******** blobfuse[1027432]: Initializing blobfuse using BlockBlob
Jun  1 10:02:28 usa******** blobfuse[1027432]: Setup storage client
Jun  1 10:02:28 usa******** blobfuse[1027432]: Kernel version is 4.180000
Jun  1 10:02:28 usa******** blobfuse[1027432]: libcurl version is 7.610000
Jun  1 10:02:28 usa******** blobfuse[1027432]: ** Delaying authentication to post fork for older curl versions
^C
[root@usa******** log]# date;
Wed Jun  1 10:05:56 UTC 2022

**Comment by vibhansa-msft** [comment] 2022-06-01 10:34
You are saying it was working with 1.4.1 and after the upgrade it has stopped working?

**Comment by vibhansa-msft** [comment] 2022-06-01 10:35
Can you share logs after the line "Delaying authentication to post fork ". If you see some requests going and coming back with response status "0" then blobfuse is not able to connect to azure.

**Comment by GunaGopal** [comment] 2022-06-01 10:41
Hi Vibhansa,

Initially we have installed 1.4.1 version and it was working and later a week ago it stopped working, so I tried to configure again but when I execute the blobfuse mount command it got hung and not showing any output, when I checked the logs it was showing only the above mentioned details.

IT took time so I cancelled and if I list the files in the mounted directory it was throwing below error and the mount directory showing this permissions

[root@USA****** blobfuse]# ll
**ls: cannot access 'datafiles': Transport endpoint is not connected**
total 5684
-rw-r--r-- 1 root root 5813484 Jan 13 12:12 blobfuse-1.4.3-RHEL-8.2-x86_64.rpm
**d????????? ? ?    ?          ?            ? datafiles**
-rw------- 1 root root     160 Jun  1 06:22 fuse_connection.cfg
drwxrwx--- 2 root root       6 May 30 15:14 root
drwxrwxrwx 3 root root      18 May 31 06:40 temp


In logs directory I don't see any logs after this and there is no response as well

**Comment by souravgupta-msft** [comment] 2022-06-01 10:52
Can you share your config file?
Also can you try running the mount command with -d flag and share the logs.

**Comment by GunaGopal** [comment] 2022-06-01 10:58
Unable to use -d flag argument.

[root@USA********** blobfuse]# blobfuse datafiles --tmp-path=/opt/data/softwares/blobfuse/temp  --config-file=/opt/data/softwares/blobfuse/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other --log-level=LOG_DEBUG --d flag
fuse: invalid argument `flag'
[root@USA******* blobfuse]# cat fuse_connection.cfg
accountName npddelphi***amesa
accountKey ***************==
containerName datafiles

**Comment by souravgupta-msft** [comment] 2022-06-01 16:47
@GunaGopal, while the above command is running, can you try to run **ls** command in the mounted directory in a different shell. Let us know what it outputs. At the same time, it should also add some logs.

**Comment by souravgupta-msft** [comment] 2022-06-02 06:22
When you run the above command, you should also see some logs in the console

**Comment by GunaGopal** [comment] 2022-06-02 06:38
@souravgupta-msft - I have replicated the steps as you mentioned but while executing the mount command I'm unable to switch to the mounted directory, the terminal got hung and showing no output.

Below are the output:

[root@USAZUAUDDE04776 blobfuse]# cd datafiles
-bash: cd: datafiles: Transport endpoint is not connected
[root@USAZUAUDDE04776 blobfuse]# ls
ls: cannot access 'datafiles': Transport endpoint is not connected
blobfuse-1.4.3-RHEL-8.2-x86_64.rpm  datafiles  fuse_connection.cfg  root  temp  testing
[root@USA********** blobfuse]# ll
ls: cannot access 'datafiles': Transport endpoint is not connected
total 5684
-rw-r--r-- 1 root root 5813484 Jan 13 12:12 blobfuse-1.4.3-RHEL-8.2-x86_64.rpm
d????????? ? ?    ?          ?            ? datafiles
-rw------- 1 root root     160 Jun  1 06:22 fuse_connection.cfg
drwxrwx--- 2 root root       6 May 30 15:14 root
drwxrwxrwx 3 root root      18 May 31 06:40 temp
drwxrwxrwx 2 root root       6 May 30 15:49 testing

Logs are showing the same details, please find below logs:

Jun  2 06:32:40 usa******** blobfuse[1524715]: Using syscall to detect directory is already mounted or not
Jun  2 06:32:40 usa******** blobfuse[1524715]: Account name found
Jun  2 06:32:40 usa******** blobfuse[1524715]: Account Key found
Jun  2 06:32:40 usa******** blobfuse[1524715]: Container name found
Jun  2 06:32:40 usa******** blobfuse[1524715]: Setting logging level to : LOG_DEBUG
Jun  2 06:32:40 usa******** blobfuse[1524715]: Disk Thresholds : 90 - 80, Cache Eviction : 1000-0, List Cancel time : 0 Retry Policy (0, 60.000000, 1.200000), Background Download 0, Evict on sync 0
Jun  2 06:32:40 usa******** blobfuse[1524715]: Blobfuse version : 1.4.3
Jun  2 06:32:40 usa******** blobfuse[1524715]: release is 4.180000, Kernel version is 4.18.0-193.14.3.el8_2.x86_64
Jun  2 06:32:40 usa******** blobfuse[1524715]: CURL Version is 7.61.1
Jun  2 06:32:40 usa******** blobfuse[1524715]: ** Delaying tls init to post fork for older libcurl version
Jun  2 06:32:40 usa******** blobfuse[1524715]: Function ensure_files_directory_exists_in_cache, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /opt.
Jun  2 06:32:40 usa******** blobfuse[1524715]: Function ensure_files_directory_exists_in_cache, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /opt/data.
Jun  2 06:32:40 usa******** blobfuse[1524715]: Function ensure_files_directory_exists_in_cache, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /opt/data/softwares.
Jun  2 06:32:40 usa******** blobfuse[1524715]: Function ensure_files_directory_exists_in_cache, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /opt/data/softwares/blobfuse.
Jun  2 06:32:40 usa******** blobfuse[1524715]: Function ensure_files_directory_exists_in_cache, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /opt/data/softwares/blobfuse/temp.
Jun  2 06:32:40 usa******** blobfuse[1524715]: Function ensure_files_directory_exists_in_cache, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /opt/data/softwares/blobfuse/temp/root.
Jun  2 06:32:40 usa******** blobfuse[1524715]: Initializing blobfuse using BlockBlob
Jun  2 06:32:40 usa******** blobfuse[1524715]: Setup storage client
Jun  2 06:32:40 usa******** blobfuse[1524715]: Kernel version is 4.180000
Jun  2 06:32:40 usa******** blobfuse[1524715]: libcurl version is 7.610000
Jun  2 06:32:40 usa******** blobfuse[1524715]: ** Delaying authentication to post fork for older curl versions

**Comment by souravgupta-msft** [comment] 2022-06-02 08:37
When you mount blobfuse with "-d" option, it will mount in foreground and hence your terminal will be blocked until unmount is done.  Once you mount with this flag, use another terminal to check your file IO and while any read/write operation is in progress you will see some logs on the blobfuse console as well as in the log files.  If this also does not show any signs of logs, can you try another cli option "--pre-mount-validate=true". As logs are not getting updated, we are not able to analyze the failure.

**Comment by GunaGopal** [comment] 2022-06-02 08:48
Yes, we are unable to check any logs or list files in the mounted directory until it is unmounted. I have tried the cli option which you have mentioned and I got the below output

[root@USA***** blobfuse]# blobfuse datafiles --tmp-path=/opt/data/softwares/blobfuse/temp  --config-file=/opt/data/softwares/blobfuse/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other --log-level=LOG_DEBUG --pre-mount-validate=true
**fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option**
[root@USA****** blobfuse]# ll
total 5684
-rw-r--r-- 1 root root 5813484 Jan 13 12:12 blobfuse-1.4.3-RHEL-8.2-x86_64.rpm
drwxrwxrwx 2 root root      38 Jun  2 06:33 datafiles
-rw------- 1 root root     160 Jun  1 06:22 fuse_connection.cfg
drwxrwx--- 2 root root       6 May 30 15:14 root
drwxrwxrwx 3 root root      18 May 31 06:40 temp
drwxrwxrwx 2 root root       6 May 30 15:49 testing
[root@USA**** blobfuse]# cd datafiles/
[root@USA**** datafiles]# ll
total 0
 
Below are the logs for the same:

Jun  2 08:43:00 usa******** blobfuse[1570884]: Using syscall to detect directory is already mounted or not
Jun  2 08:43:00 usa******** blobfuse[1570884]: Account name found
Jun  2 08:43:00 usa******** blobfuse[1570884]: Account Key found
Jun  2 08:43:00 usa******** blobfuse[1570884]: Container name found
Jun  2 08:43:00 usa******** blobfuse[1570884]: Setting logging level to : LOG_DEBUG
Jun  2 08:43:00 usa******** blobfuse[1570884]: Pre mount validation enabled
Jun  2 08:43:00 usa******** blobfuse[1570884]: Disk Thresholds : 90 - 80, Cache Eviction : 1000-0, List Cancel time : 0 Retry Policy (0, 60.000000, 1.200000), Background Download 0, Evict on sync 0
Jun  2 08:43:00 usa******** blobfuse[1570884]: Blobfuse version : 1.4.3
Jun  2 08:43:00 usa******** blobfuse[1570884]: release is 4.180000, Kernel version is 4.18.0-193.14.3.el8_2.x86_64
Jun  2 08:43:00 usa******** blobfuse[1570884]: CURL Version is 7.61.1
Jun  2 08:43:00 usa******** blobfuse[1570884]: ** Delaying tls init to post fork for older libcurl version
Jun  2 08:43:00 usa******** blobfuse[1570884]: Function ensure_files_directory_exists_in_cache, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /opt.
Jun  2 08:43:00 usa******** blobfuse[1570884]: Function ensure_files_directory_exists_in_cache, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /opt/data.
Jun  2 08:43:00 usa******** blobfuse[1570884]: Function ensure_files_directory_exists_in_cache, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /opt/data/softwares.
Jun  2 08:43:00 usa******** blobfuse[1570884]: Function ensure_files_directory_exists_in_cache, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /opt/data/softwares/blobfuse.
Jun  2 08:43:00 usa******** blobfuse[1570884]: Function ensure_files_directory_exists_in_cache, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /opt/data/softwares/blobfuse/temp.
Jun  2 08:43:00 usa******** blobfuse[1570884]: Function ensure_files_directory_exists_in_cache, in file /usr/pipeline/blobfuse/azure-storage-fuse/blobfuse/utilities.cpp, line 96: Making cache directory /opt/data/softwares/blobfuse/temp/root.
Jun  2 08:43:00 usa******** blobfuse[1570884]: Initializing blobfuse using BlockBlob
Jun  2 08:43:00 usa******** blobfuse[1570884]: Setup storage client
Jun  2 08:43:00 usa******** blobfuse[1570884]: Kernel version is 4.180000
Jun  2 08:43:00 usa******** blobfuse[1570884]: libcurl version is 7.610000
Jun  2 08:43:00 usa******** blobfuse[1570884]: Authenticating using account key
Jun  2 08:43:00 usa******** blobfuse[1570884]: ==> REQUEST/RESPONSE :: GET https://npddelphitcsbancsamesa.blob.core.windows.net/datafiles?comp=list&delimiter=/&include=metadata&maxresults=1&restype=container?&User-Agent=azure-storage-fuse/1.4.3&x-ms-date=Thu, 02 Jun 2022 08:43:00 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 200 :: REQ ID : e7e3aa1e-201e-0067-0a5c-769fa4000000
Jun  2 08:43:00 usa******** blobfuse[1570884]: Successfully Authenticated!

**Comment by GunaGopal** [comment] 2022-06-02 11:23
@souravgupta-msft in the logs it is showing successfully authenticated but the files are not synced with storage account.

**Comment by GunaGopal** [comment] 2022-06-02 13:01
I have tried installing the blob fuse in the other VM and with different storage account but still facing the same issue. Here the blob fuse version is 1.4.1 and linux version is Redhat 8.2

Jun  2 12:46:31 usa******** blobfuse[2671100]: Using syscall to detect directory is already mounted or not
Jun  2 12:46:31 usa******** blobfuse[2671100]: Setting logging level to : LOG_DEBUG
Jun  2 12:46:31 usa******** blobfuse[2671100]: Pre mount validation enabled
Jun  2 12:46:31 usa******** blobfuse[2671100]: Disk Thresholds : 90 - 80, Cache Eviction : 1000-0, List Cancel time : 0 Retry Policy (0, 60.000000, 1.200000), Background Download 0, Evict on sync 0
Jun  2 12:46:31 usa******** blobfuse[2671100]: Blobfuse version : 1.4.1
Jun  2 12:46:31 usa******** blobfuse[2671100]: release is 4.180000, Kernel version is 4.18.0-193.14.3.el8_2.x86_64
Jun  2 12:46:31 usa******** blobfuse[2671100]: CURL Version is 7.61.1
Jun  2 12:46:31 usa******** blobfuse[2671100]: ** Delaying tls init to post fork for older libcurl version

**Comment by souravgupta-msft** [comment] 2022-06-03 05:49
@GunaGopal try out the following:
1. Run the mount command. When the blobfuse logs are not coming can you check if the binary is running using this command: "ps -aux | grep blobfuse"
2. Run **df** command to see if your local directory is mounted or not using blobfuse
3. Also can you please verify if you are able to connect to Azure Storage using some other means like azcli or azcopy

**Comment by GunaGopal** [comment] 2022-06-03 16:19
I have executed the above commands and still I don't see any update in logs.
****ZUAUDDE04776 blobfuse]# blobfuse datafiles --tmp-path=/opt/data/softwares/blobfuse/temp  --config-file=/opt/data/softwares/blobfuse/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other --log-level=LOG_DEBUG --pre-mount-validate=true
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option
[blob_logs.txt](https://github.com/Azure/azure-storage-fuse/files/8834089/blob_logs.txt)



I have also tried the azcopy command, with this I'm able to download the files from the container using the same account key

**Comment by vibhansa-msft** [comment] 2022-06-04 07:41
Are you mounting with sudo, if no can you give that a try. As logs are not coming at all, I suspect mount is not going through fine. Also in above thread you mentioned that it was working earlier, any idea what has changed at system level that led us to this issue.

One more option is to give our next-gen blobfuse (Blobfuse2) a try (https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse2-2.0.0-preview.1). This requires configuration to be done in little different way and uses libfuse3 driver. You can refer readme for Blobfuse2 here (https://github.com/Azure/azure-storage-fuse/tree/main). However this is still in preview mode.

**Comment by vibhansa-msft** [comment] 2022-06-04 07:42
Also just to confirm, your setup does not involve any sort of proxy?

**Comment by GunaGopal** [comment] 2022-06-06 06:34
Hi @vibhansa-msft - I have tried mounting with sudo as well but still it is not working as expected, below is the output of the command and no additional logs were traced.

[root@USA******* blobfuse]# sudo blobfuse datafiles --tmp-path=/opt/data/softwares/blobfuse/temp  --config-file=/opt/data/softwares/blobfuse/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other --log-level=LOG_DEBUG --pre-mount-validate=true
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option.

**Comment by vibhansa-msft** [comment] 2022-06-06 06:41
"Mountpoint not empty" is a different error then the issue you are facing. It just tells that the mount directory you have given is not empty and hence mount cannot succeed. In such cases just clean-up the mount directory and retry.

**Comment by GunaGopal** [comment] 2022-06-06 06:58
I have unmounted and removed the mounted directory (datafiles), created new directory and tried executing the below command but still facing the same issue. And I have exited and when I'm listing the files I'm getting "Transport endpoint not connected"

Below are the logs for the same:

[root@USA******** blobfuse]# sudo blobfuse datafiles --tmp-path=/opt/data/softwares/blobfuse/temp  --config-file=/opt/data/softwares/blobfuse/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other --log-level=LOG_DEBUG --pre-mount-validate=true
^C
[root@USA******* blobfuse]# ll
**ls: cannot access 'datafiles': Transport endpoint is not connected**
total 5684
-rw-r--r-- 1 root root       0 Jun  3 16:15 asdasda.txt
-rw-r--r-- 1 root root 5813484 Jan 13 12:12 blobfuse-1.4.3-RHEL-8.2-x86_64.rpm
**d????????? ? ?    ?          ?            ? datafiles**

**Comment by vibhansa-msft** [comment] 2022-06-06 07:09
"Transport endpoint not connected": generally, comes when blobfuse binary has terminated abruptly. Can you enable core dumping in your system so that if blobfuse crashes we can get a core file and analyze where its failing?

**Comment by vibhansa-msft** [comment] 2022-06-06 07:13
Also post mount when you did "ll" I see there are two files listed, please confirm they are there in your container. Just want to check that we are trying to retrieve something from the container. 
Just to double check the logging issue copy this file to /etc/rsyslog.d directory and restart rsyslogd service. Want to make sure that logs are not going to any other place and hence we feel its missing completly.
https://github.com/Azure/azure-storage-fuse/blob/master/systemd/10-blobfuse.conf
Command to copy  "sudo cp ./systemd/10-blobfuse.conf /etc/rsyslog.d/"
Command to restart rsyslogd "sudo service rsyslog restart"

**Comment by GunaGopal** [comment] 2022-06-06 11:15
I have configured the logs as mentioned above and still I could see only the same set of logs

**Comment by vibhansa-msft** [comment] 2022-06-07 02:21
Did you get a chance to try out core dumping?
Just to unblock you, if possible, give blobfuse2 a try. You just need to install fuse3 on your system and install our v2 binaries. You can download rpm from our release page.  We have a command compatibility mode where you can just say "blobfuse2 mountv1 " and provide all the arguments that you give to blobfuse command. It will auto generate yaml config required for v2 and mount. You can refer https://github.com/Azure/azure-storage-fuse/blob/main/README.md if you interested in this.

**Comment by vibhansa-msft** [comment] 2022-06-09 02:30
Were you able to give blobfuse2 a try ?

**Comment by GunaGopal** [comment] 2022-06-09 07:37
Hi @vibhansa-msft, 

We have tried installing the blobfuse2 in one of our environment, the command gets completed and it is mounted but when I try to move or list the files in the mounted directory, the command wasn't not showing any output/ not responding. Attached the logs for your reference.
[blobfuse2.log](https://github.com/Azure/azure-storage-fuse/files/8867993/blobfuse2.log)

**Comment by vibhansa-msft** [comment] 2022-06-09 09:45
Thanks for sharing the logs. With Blobfuse2 atleast we are getting the logs. I can see below line in the shared log file
"Jun  9 07:20:03 usazuaudde04748 blobfuse2[2204330]: LOG_INFO [libfuse_handler.go (116)]: Libfuse::initFuse : Mounting with fuse3 library"

Post this we expect libfuse library to mount the FS and call us back to begin our processing. However in logs I do not see that call coming. It shall look something like " Libfuse::libfuse3_init : init", which is missing.
This points to some situation in your pod/vm where fuse driver is not able to function properly. Either its some setup issue with fuse or some system level permission issue. Can you share how did you install the fuse driver. If not sure try "sudo yum install fuse3 fuse3-devel".
As per logs we are clear that blobfuse is not getting a call back to start its operation.

**Comment by vibhansa-msft** [comment] 2022-06-09 09:48
If the setup is something similar to containers or AKS then we need to give some sort of privileged access while creating the container. Please check you have sufficient permissions to use fuse on this system.
"--cap-add SYS_ADMIN" is the cli param to be added while creating the container.

**Comment by vibhansa-msft** [comment] 2022-06-10 06:21
For Azure VMs we have our nightly pipeline setup for RHEL 8.2 and we do not face any problem there. Just for the cross-check can you give this a try on Ubuntu-20 VM? Just want to make sure its some environment specific issue or not. We do support RHEL7.5/7.8 as well if you want to stick to RHEL.

**Comment by vibhansa-msft** [comment] 2022-06-14 07:55
Were you able to try out on Ubn or older RHEL versions ?

**Comment by GunaGopal** [comment] 2022-06-14 13:17
Yes we are using ARM template to provision the Azure VM's

**Comment by vibhansa-msft** [comment] 2022-06-15 03:30
If you can share the template with us, we can try to reproduce this issue locally and investigate further. We have earlier tried creating a RHEL 8.2 VM through Azure portal (without any template, basic config) and we do not see any issue there.

**Comment by vibhansa-msft** [comment] 2022-06-20 06:29
If the issue still persists kindly share the arm template. We are not able to reproduce this locally.

**Comment by vibhansa-msft** [comment] 2022-06-21 14:09
As per the ICM update, disabling "CrowdStrike" makes it work. You need to check on your end why this malware detection is blocking fuse functionality. Closing this from here. Feel free to reopen if issue persists or you have any further questions.

**Closed by vibhansa-msft** 2022-06-21 14:09 UTC
Labels: triaged
