### ISSUE TITLE
unable to mount multiple container using mount all

### ISSUE THREAD

**Issue by dipakmadhavi** [Azure/azure-storage-fuse#977] opened 2022-11-15 11:36 UTC
### Which version of blobfuse was used?

version 2.0.0-preview.5
### Which OS distribution and version are you using?
RHEL 7.9

### If relevant, please share your mount command.
blobfuse2 mount all ./test  --read-only --config-file=./config.yaml

config.yaml
.
.
.
azstorage:
  type: block
  account-name: mask
  account-key: xxxxxxxx
  endpoint: https://xxxxxxxxxxxxxxx.blob.core.windows.net/
  mode: key
mountall:
  container-allowlist:
  -  container1 container2

### What was the issue encountered?

single container mounted wihtout any issue. Using mountall not able to mount and no error on screeen

### Have you found a mitigation/solution?
no

**Comment by vibhansa-msft** [comment] 2022-11-15 16:13
Duplicate of #972. Fix has already been committed to main branch, you can pull latest and build or wait for our next release.

**Closed by vibhansa-msft** 2022-11-15 16:13 UTC
Labels: V2

**Comment by dipakmadhavi** [comment] 2022-11-15 16:28
I am able to mount all container with recent build. but no listing the directory , can see only files

if we do cd and change the directory I am able to get in.

Also linux find command not working on mounted container
