### ISSUE TITLE
"Content-Type" properties was not specified during sync.

### ISSUE THREAD

**Issue by casperm** [Azure/azure-storage-fuse#159] opened 2018-04-03 16:36 UTC
items sync through blobfuse does not provide content-type properties according to files suffix. And it make  the CDN can't result the content-type correctly.

**Comment by seguler** [comment] 2018-04-04 18:29
Thanks - duplicate of #152 - let's follow up the issue there

**Closed by seguler** 2018-04-04 18:29 UTC
