### ISSUE TITLE
Blobfuse 2.0.3 is consuming increasingly high memory

### ISSUE THREAD

**Issue by hangx969** [Azure/azure-storage-fuse#1146] opened 2023-05-18 00:57 UTC
### Which version of blobfuse was used?
blobfuse2 version 2.0.3

### Which OS distribution and version are you using?
CentOS Linux release 7.7.1908 (Core)

### If relevant, please share your mount command.
blobfuse2  mount /data/blob --config-file=/path/to/config.yml

### What was the issue encountered?
1) User mounts blobfuse on virtual machine, then transfer files from local disk to blob container.
2) User finds that: every time when a transfer job is finished, the memory consuming will grow. From starting 9%, after several rounds of file transfering, it will rise to 60%. After restarting VM or restart blobfuse, memory usage will drop to <10% again.
![image](https://github.com/Azure/azure-storage-fuse/assets/104760370/d93a6d85-70db-4480-a5e5-8d53ed5d382a)

3) file trafsfer job will transfer around 200 files (pictures and videos), size of each file is 3M~10M. There are 2T data in blob container.
4) Note that this issue is initially happening on blobfuse v1, user has updated to v2 but issue still persists.

### Have you found a mitigation/solution?
Restart VM or restart blobfuse will work. But user wants to know how to adjust config to solve it.

### Please share logs if available.
1) config file:
allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

attr_cache:
  timeout-sec: 7200

file_cache:
  path: /var/cache/blobfuse

azstorage:
  type: block
  account-name: xxxxxxxx
  account-key: xxxxxx
  endpoint: xxxxxx.blob.core.chinacloudapi.cn
  mode: key
  container: ediscovery-files

**Comment by vibhansa-msft** [comment] 2023-05-19 06:57
How many files we are transferring here. If objective is to just migrate data from local system to azure storage container once, then AzCopy is a better tool to achieve this. If workflow is to transfer it on demand or sync the folders, then AzCopy has a sync option as well. If for some reason. you feel blobfuse is the correct tool here than in case of large number of files, removing "attr-cache" from the pipeline will save memory. Also, if files are just once uploaded and not read again in the same flow then you can keep "file-cache-timeout=0" so that local cache is purged immediately after the upload.

**Comment by hangx969** [comment] 2023-05-19 07:06
Hi Vibhansa,

Thanks for your suggestion. 

User is doing sync task from local to blob, during which 200 files will be transferred.
Indeed, azcopy will be a better tool. But user wants to keep using blobfuse first. If memory usage issue cannot be resolved, they might consider other tools. 

I will firstly suggest them to remove "attr-cache" and set file-cache-timeout=0, to see if issue still persists.

**Comment by vibhansa-msft** [comment] 2023-05-19 08:54
200 files shall not create much of an issue, let's try the above suggestions and see if that helps.

**Comment by hangx969** [comment] 2023-05-31 08:59
Hi Vibhansa,

User has changed config file and mount command, blobfuse has kept running for around 2 weeks. 
Right after changing was made, memory consumption is 11%, but it has raised to 33% now. 
Seems it is the same pattern as before, memory will keep raising until a reboot. 

Could you kindly share insights if other settings can be optimized? Thanks.

**mount command:** 
/usr/bin/blobfuse2 /data/blob fuse defaults,_netdev,--config-file=/path/to/config.yml,--file-cache-timeout=0

**Config file:**
allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /var/cache/blobfuse

azstorage:
  type: block
  account-name: xxxx
  account-key:
  endpoint: xxxx.blob.core.chinacloudapi.cn
  mode: key
  container: xxxx

**Comment by vibhansa-msft** [comment] 2023-06-04 07:26
Try removing "attr_cache" from "components" section in config file and check if that helps you improve memory footprints.

**Comment by hangx969** [comment] 2023-06-05 01:05
Hi @vibhansa-msft  Thanks for update! I will suggest user to remove "attr_cache" to see if it helps.

**Comment by vibhansa-msft** [comment] 2023-06-07 11:54
Can you update if that helped ?

**Comment by hangx969** [comment] 2023-06-07 11:56
Hi @vibhansa-msft , I will confirm with end user tomorrow. Thanks!

**Comment by hangx969** [comment] 2023-06-08 00:19
Hi @vibhansa-msft , after editing config file, does user have to restart blobfuse process to make changes effective?

**Comment by vibhansa-msft** [comment] 2023-06-08 02:23
Some of the configs can be loaded dynamically (depending upon the impact of the config). If we are changing the pipeline itself then you have to remount.

**Comment by hangx969** [comment] 2023-06-08 02:45
@vibhansa-msft So, after removing "attr_cache" in components, it will not need to remount to take affect, I suppose?

**Comment by vibhansa-msft** [comment] 2023-06-08 04:26
You must remount.

**Comment by hangx969** [comment] 2023-06-08 05:05
Thanks vibhansa, will sync with end user, and get back to you.

**Comment by hangx969** [comment] 2023-06-09 01:42
Hi @vibhansa-msft, user said that blobfuse was remounted 2 days ago but issue still exists. 
I wonder why the memory usage of blobfuse will not be recycled automatically, is it some kind of bug which needs fix, or are there any other factors or confgs we can adjust to mitigate issue? Thanks.

**Comment by hangx969** [comment] 2023-06-19 06:52
Hi @vibhansa-msft , hope you are doing well. Is there any update on this issue? I see milestones was set on V2.0.4  and 2.0.5, does it mean this issue will be fixed in the following versions? If yes, I might deliver to end user, so they can consider updating when new version is GA.

**Comment by vibhansa-msft** [comment] 2023-06-19 09:55
Due to other ongoing customer engagements, we were not able to investigate on why memory usage is increasing even after removing attribute-cache. As we might need to release 2.0.4 this month due to other critical fixes, we have moved this item to 2.0.5.

**Comment by vibhansa-msft** [comment] 2023-06-28 04:50
Can you share little more details on the transfer job that is being done. As mentioned in original report after the transfers are done memory remains high so if you can share details on how many files and avg of what size were transfered, I can try simulating the same in my local environment.

**Comment by hangx969** [comment] 2023-06-28 04:57
In each data transfer job, there are around 200 files (pictures and videos), size of each file is 3M~10M.

**Comment by vibhansa-msft** [comment] 2023-06-28 05:19
How frequently they are uploaded (like the job frequency)?

**Comment by vibhansa-msft** [comment] 2023-06-28 05:20
Also, in parallel is there any job running which continuously tries to list or delete these files or any other operation other then this upload job?

**Comment by vibhansa-msft** [comment] 2023-06-28 09:51
![image](https://github.com/Azure/azure-storage-fuse/assets/64532198/7b7320ed-e563-4751-8b8f-4d04809a3b67)

It has been running for 3 hours, every 10 minutes uploading and downloading 500 files of 8MB each. Do not see any issue in terms of memory usage here.

**Comment by vibhansa-msft** [comment] 2023-06-28 09:59
Will bump up the test to create 500 files of 100MB each and lets see how it reacts. We have done this kind of testing earlier and it increases for some time and then stablises at certain point. Go being a GCed language to some extent this is expected.

Below is a sample command I am using to generate the data:

"for i in {1..500}; do echo $i; done | parallel --will-cite -j 20 'head -c 100M < /dev/random > /home/vibhansa/blob_mnt2/myfile_small_{}'"

**Comment by vibhansa-msft** [comment] 2023-06-29 05:00
System was running whole night doing upload/download 100s of file every 5 minutes. I do not see any sort of memory spikes.
![image](https://github.com/Azure/azure-storage-fuse/assets/64532198/86567a96-b597-459a-a704-fce708de6e6c)

**Comment by vibhansa-msft** [comment] 2023-07-10 07:21
I am still not able to reproduce this locally. Even after running system for few days, I do not see any memory spikes. Can you try our latest release and confirm you are still hitting the issue or not.

**Comment by hangx969** [comment] 2023-07-10 07:45
Will contact end user to see if he can try using the latest version to verify. Thanks!

**Comment by vibhansa-msft** [comment] 2023-08-14 05:25
Closing this as there is no update. Feel free to reopen once required information is available.

**Closed by vibhansa-msft** 2023-08-14 05:25 UTC
Labels: bug, triaged, V2
