### ISSUE TITLE
Ubuntu 18.04 - blobfuse 1.2.1 randomly gets "Transport endpoint is not connected"

### ISSUE THREAD

**Issue by cris-b** [Azure/azure-storage-fuse#370] opened 2020-03-05 11:01 UTC
### Which version of the blobfuse was used?

1.2.1

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?

We have a nightly run which creates a vm in azure which uses blob storage for writing via blobfuse.  Since 26th feb the creation of the server was picking up the new blobfuse 1.2.1 release, and we started experiencing 'Transport endpoint is not connected' causing the writes to fail and the run to fail.   

Reverting to 1.1.1 made behaviour as before.

### Have you found a mitigation/solution?

Revert to 1.1.1

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

Nothing i can see in the syslog.

### If relevant, please share your mount command.

mounting via storage account key.

**Comment by amnguye** [comment] 2020-03-05 17:56
Hi,

Thanks for bringing this issue up.

So does this error appears, does it appear when you attempt to mount? Or is this after you've successfully mounted and it appears after you try to write to files?

When you say that you've mounted via storage account key, does that mean you've specified a configuration file to get that information from or do you specify that in the environment varaibles?

**Comment by sashman-jaspin** [comment] 2020-03-16 18:36
I'm hitting this issue as well and can replicate it. We have a backup function that copies veeam backups across blobfuse. It works fine when we only copy a few files at a time, but with any large load it errors with "Transport endpoint is not connected" and we need to remount it. The files are quite large 200GB to 2TB.

Copy script --
#!/bin/bash find /backups/aba -type f \( -iname '*.vib' -or -iname '*.vbk' \) -mtime -5 -exec cp -n {} ~/abablob \;

Mount --
blobfuse abablob --tmp-path=/backups/tmp --config-file=fuse_connection.cfg --use-https=true --log-level=LOG_DEBUG -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120

OS --
Ubuntu 16.04.12

Blobfuse --
blobfuse/xenial,now 1.2.1 amd64 [installed]

Network --
No NATs, direct

Disk --
Straight 4TB SAS, believe 10k raid10. ext4

**Comment by sashman-jaspin** [comment] 2020-03-17 10:34
Looks like solution to this is to uninstall 1.2.1 and reistall 1.1.1.  1.2.1 is faulting constantly for me.

**Comment by amnguye** [comment] 2020-03-17 16:32
Could you also enable debug logging "--log-level=LOG_DEBUG" then we can see what any errors or logging within the syslog. If this happens within a few minutes then we will easily be able to see the errors. Without this information it's difficult to determine where the problem is.

**Comment by sashman-jaspin** [comment] 2020-03-17 18:28
I actually run it with debug on, and there is a log file attached to the above.   I was able to narrow in a bit.  It is segfaulting a few minutes into put operations.  It also seems to be the same file(s).  I gave up after several attempts to move one file over.  Uninstalled and installed 1.1.1 and it worked fine.  

mount 
simple cp 
.. 30 seconds of puts ..
Mar 17 05:36:41 veeam-1 blobfuse[11430]: Tue Mar 17 05:36:41 2020 ==> REQUEST/RESPONSE#012#011PUT
Mar 17 05:36:44 veeam-1 systemd[9829]: Received SIGRTMIN+24 from PID 17664 (kill).

**Comment by toothache** [comment] 2020-04-10 07:04
I'm hitting this issue on Azure Batch as well. We mounted several blob storages in the Batch Pool. Everything went well before. However, we frequently hit "Transport endpoint is not connected" or "File not found" errors starting from this week. The blobfuse version is also 1.2.1.

OS:
Canonical UbuntuServer 18.04-LTS (latest)

VM size:
standard_ds3_v2

Blobfuse mount options:
-o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other

Blobfuse version:
v1.2.1

**Comment by NaraVen** [comment] 2020-04-10 07:06
If you do not need Managed Identity features then I recommend you downgrade to 1.1.1

**Comment by toothache** [comment] 2020-04-10 07:16
How can I specify the blobfuse version in Batch Pool creation? It seems not configurable.

**Comment by NaraVen** [comment] 2020-04-10 07:38
> How can I specify the blobfuse version in Batch Pool creation? It seems not configurable.

you will have to manually remove 12.1 and add 1.1.1

**Comment by cj901014** [comment] 2020-05-12 09:11
@vibhansa-msft 

Hi, Vikas. Any update about this issue?

**Comment by vibhansa-msft** [comment] 2020-05-12 09:21
When this error is hit confirm 'blobfuse' process is still running. I am not able to reproduce the exact same case, however I observe the same errors when blobfuse terminates unexpectedly.

**Comment by vibhansa-msft** [comment] 2020-06-01 04:55
blobfuse 1.2.3 has just been released with bug fixes and enhancements. Kindly try this version out and  confirm issue has been resolved or still hit.

**Comment by vibhansa-msft** [comment] 2020-06-14 03:47
Closing this as no update has been received. If issue is still hit with latest version also, kinly reopen this thread.

**Comment by leonardomiranda13** [comment] 2020-06-19 17:44
/reopen

Hi Guys, I'm facing the same problem, but with CentOS 6.10.

Blobfuse - 1.0.2-1    
Fuse - 2.8.3-5.el6

I really don't know what could cause this issue, but my VM are able to reach the blob.

**Comment by vibhansa-msft** [comment] 2020-06-20 03:04
Kindly use the latest version as this issue has been addressed in 1.2.3 version.

**Comment by leonardomiranda13** [comment] 2020-06-20 04:32
Microsoft has dropped a new package to CentOS 6? Because at this afternoon, the version that I currently use was the last version available at MS repo.

**Comment by vibhansa-msft** [comment] 2020-06-20 04:50
For now version 1.2.3 is released only for Ubuntu 16.04 and 18.04. We are working on RHEL release. You can take the latest code base and give it a try, in case you are stuck with the issue.

**Comment by MarianoFacundoArch** [comment] 2020-07-07 18:33
Same bug on 1.2.3 here

**Comment by MarianoFacundoArch** [comment] 2020-07-07 18:33
I am downgrading again to 1.1.1 .

**Comment by MarianoFacundoArch** [comment] 2020-07-08 11:45
No bugs on 1.1.1 .
I don't know what changed since 1.1.1 but it's getting impossible to use it

**Comment by vibhansa-msft** [comment] 2020-07-08 12:54
@MarianoFacundoArch we have seen this error only when 'blobfuse' terminates abruptly. When this error is hit can you check the pid of blobfuse exists or not. Can you share what  operations were being done which resulted in this error. Also share the syslogs around the time this error was hit.

**Comment by MarianoFacundoArch** [comment] 2020-07-09 16:49
It is an instance connected to a nextcloud server, so it's impossible to figure out what was exactly going on as I notice it when I try to access my nextcloud instance and it notes that the data dir is not accessible. 
I don't know why but 1.1.1 has no bugs, but from that version onwars, this keeps happening and has not been fixed.
Only solution is rollback to 1.1.1

**Comment by vibhansa-msft** [comment] 2020-07-09 17:09
If its possible collect the syslog around the time when it terminated. From syslog you can filter out 'blobfuse' logs and the last few logs shall be around the time it terminated. It may give some hint on what was going on.

**Comment by vibhansa-msft** [comment] 2020-09-01 16:53
Lot of enhancements and bug fixes have been done in 1.3.1. Kindly try the latest version and reopen if the issue still persists.

**Closed by vibhansa-msft** 2020-09-01 16:53 UTC
Labels: bug

**Comment by matt-sdc** [comment] 2020-09-18 16:48
I'm getting this error on blobfuse 1.3.2.  We got it ~4 hours after mounting the drive. I'll try downgrading as well and seeing if that fixes it

**Comment by NaraVen** [comment] 2020-09-18 17:19
@matt-sdc, could you tell me a little about your setup. Are you running on a VM.? How much memory does your machine have available? If possible could you please send your syslog.
