### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by hieuhoang** [Azure/azure-storage-fuse#558] opened 2021-01-27 05:15 UTC
### Which version of the blobfuse was used?
blobfuse 1.3.6

### Which OS (please include version) are you using?
Ubuntu 20.04

### What problem was encountered?
blobfuse occasionally segfault. Subsequent access to the mount would give the message
   Transport endpoint is not connected

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Jan 26 20:21:38 mt-gpu-001 blobfuse[894387]:  ==> REQUEST/RESPONSE :: HEAD https://hieustorage2.blob.core.windows.net/hieublob2/hieu/workspace/experiment/issues/data-collection/laser-url/hpc/en-lt/config.en-lt.yaml?&User-Agent=azure-storage-fuse/1.3.6&x-ms-date=Wed, 27 Jan 2021 04:21:38 GMT&x-ms-version=2018-11-09&Authorization=****&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 400 ::
Jan 26 20:21:38 mt-gpu-001 kernel: [889872.773486] traps: blobfuse[1023085] general protection fault ip:55bbf875b4e9 sp:7f180dff96a0 error:0 in blobfuse[55bbf86e3000+140000]

### If relevant, please share your mount command.
    blobfuse $MOUNT_POINT --tmp-path=/tmp/blobfuse/$MOUNT_POINT  --config-file=$CFG_FILE -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other

**Comment by vibhansa-msft** [comment] 2021-01-27 12:09
During any specific operation you observe the segfault ? Can you enable debug logs and share the log files when it crashes.

**Comment by hieuhoang** [comment] 2021-01-28 03:58
It usually happens when I try to kill an IO-bound process.  You want me to run blobfuse with --log-level=LOG_ERR ? 

Will do when I restart the server, it's heavily used at the moment

**Comment by vibhansa-msft** [comment] 2021-01-28 04:00
--log-level=LOG_DEBUG is what I suggest. Also I am unable to reproduce this locally so if you can give me some steps on how to hit it, it will be helpful to root-cause.

**Comment by hieuhoang** [comment] 2021-01-28 04:01
sure thing

**Comment by vibhansa-msft** [comment] 2021-03-08 11:08
Are you still hitting the issue ? we are not able to reproduce this locally.

**Comment by vibhansa-msft** [comment] 2021-03-16 03:16
Closing the issue as there is no update. Feel free to reopen if its still hit.

**Closed by vibhansa-msft** 2021-03-16 03:16 UTC
Labels: bug

**Comment by hieuhoang** [comment] 2021-03-16 03:19
apologies, I'm still getting the issue but don't have time to debug it as it always happens at the worse possible time when the server is very busy and need to get it back up.

Will re-open if I can put together a reproducable scenario

**Comment by vibhansa-msft** [comment] 2021-03-16 04:02
Sure, kindly share the steps once you are able to reproduce it consistently. Also I suggest to monitor the memory usage and disk usage (for cache directory) when your test cases are running. Just suspecting these might be playing some role in random crash.
