### ISSUE TITLE
Blob access is slow when using Blobfuse with Msi Authentication

### ISSUE THREAD

**Issue by sweana** [Azure/azure-storage-fuse#377] opened 2020-04-02 03:31 UTC
### Which version of the blobfuse was used?
1.2.1

### Which OS (please include version) are you using?
Ubuntu 16.04

### What problem was encountered?
Blob access is slow when using Blobfuse with Msi Authentication. Looks like for each blob access, blobfuse is requesting a token from MsiEndpoint. The token has an Expiry field. Blobfuse should only request a token when the token hasn't expired yet. The MsiEndpoint anyway returns the same token to Blobfuse until it expires. As a result, each access that should take milli seconds, now takes minutes and this delay adds up quickly.

**Comment by NaraVen** [comment] 2020-04-02 08:43
Hi Sweta,
     We will create a bug for this. I checked the code, it is honoring the expiresOn property of the token however, it is not comparing against current UTC time. We will take care of this.
Thank you for surfacing it,
Nara

**Comment by NaraVen** [comment] 2020-04-05 17:41
Hi Swetha,
     This is not a bug. I checked the exact code against release 1.2.1 and the token is always reused. It is never reissued. I can share my tests with you. If you are good with this we can close this bug. The Token endpoint verification is called by Azure Storage service. This is to make sure that the token carrier indeed has access to each of the blobs in the container. Tokens are not reissued.
Nara

**Comment by NaraVen** [comment] 2020-04-25 07:27
Latest release has fixed this bug.

**Closed by NaraVen** 2020-04-25 07:27 UTC
