### ISSUE TITLE
Syslog loop errors  : "WatchConfig : Config change detected"

### ISSUE THREAD

**Issue by arkpoah** [Azure/azure-storage-fuse#1291] opened 2023-11-23 16:26 UTC
### Which version of blobfuse was used?
2.1.2

### Which OS distribution and version are you using?
Debian 10

### If relevant, please share your mount command.
blobfuse2 mount /mnt/ --config-file=/etc/blobfuse2/test.yaml --log-level=LOG_WARNING

### What was the issue encountered?
Mount is well done and seems working correctly but I get loop errors in logs : 
```
Nov 23 16:21:16 xxxxx blobfuse2[28979]: LOG_CRIT [config_parser.go (160)]: WatchConfig : Config change detected
Nov 23 16:21:16 xxxxx blobfuse2[28979]: LOG_CRIT [mount.go (174)]: Log level reset to : LOG_WARNING
Nov 23 16:21:16 xxxxx blobfuse2[28979]: LOG_CRIT [config_parser.go (160)]: WatchConfig : Config change detected
Nov 23 16:21:16 xxxxx blobfuse2[28979]: LOG_CRIT [mount.go (174)]: Log level reset to : LOG_WARNING
Nov 23 16:21:17 xxxxx blobfuse2[28979]: LOG_CRIT [config_parser.go (160)]: WatchConfig : Config change detected
Nov 23 16:21:17 xxxxx blobfuse2[28979]: LOG_CRIT [mount.go (174)]: Log level reset to : LOG_WARNING
Nov 23 16:21:17 xxxxx blobfuse2[28979]: LOG_CRIT [config_parser.go (160)]: WatchConfig : Config change detected
Nov 23 16:21:17 xxxxx blobfuse2[28979]: LOG_CRIT [mount.go (174)]: Log level reset to : LOG_WARNING
Nov 23 16:21:19 xxxxx blobfuse2[28979]: LOG_CRIT [config_parser.go (160)]: WatchConfig : Config change detected
Nov 23 16:21:19 xxxxx blobfuse2[28979]: LOG_CRIT [mount.go (174)]: Log level reset to : LOG_WARNING
Nov 23 16:21:19 xxxxx blobfuse2[28979]: LOG_CRIT [config_parser.go (160)]: WatchConfig : Config change detected
Nov 23 16:21:19 xxxxx blobfuse2[28979]: LOG_CRIT [mount.go (174)]: Log level reset to : LOG_WARNING
```

### Have you found a mitigation/solution?
Disable logs, but not relevant solution

### Please share logs if available.
See above

### My config file
```
allow-other: true

logging:
  type: syslog
  level: LOG_WARNING
  track-time: true

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /tmp/fuse_tempcache
  timeout-sec: 60
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:
  type: adls
  account-name: xxxx
  account-key: xxxx
  endpoint: https://xxxx.blob.core.windows.net/
  mode: key
  container: xxxx
  subdirectory: xxxx
```

Thanks

**Comment by vibhansa-msft** [comment] 2023-11-24 03:18
Your config file is "/etc/blobfuse2/test.yaml ". Is there any process or application which is touching this file continuously?
These messages are coming from a file-change notifier module which kicks in whenever the config file is modified.

**Comment by vibhansa-msft** [comment] 2023-11-27 05:33
Closing this as these logs are caused by change in the config file. Customer needs to check why the config file is touched so frequently.

**Closed by vibhansa-msft** 2023-11-27 05:33 UTC
Labels: V2, user-error

**Comment by arkpoah** [comment] 2023-11-27 09:38
Indeed, config file is managed by consul-templaterb which watches it. Content does not change but something happens on file.
I confirm I don't reproduce the issue with a static config file.
