### ISSUE TITLE
fuse: mount failed: Permission denied

### ISSUE THREAD

**Issue by techsaau** [Azure/azure-storage-fuse#422] opened 2020-06-15 08:09 UTC
### Which version of the blobfuse was used?
blobfuse 1.2.3

### Which OS (please include version) are you using?
VERSION="20.04 LTS (Focal Fossa)"

### What problem was encountered?
I'm trying to use blobfuse in Azure Container Instances. But every-time i receive below error while try to execute blobfuse command to mount:
fuse: mount failed: Permission denied

### Have you found a mitigation/solution?
NO

### If relevant, please share your mount command.
blobfuse /root/fileshare --tmp-path=/mnt/resource/blobfusetmp  --config-file=/root/fuse_connection.cfg -o allow_other -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120

**Comment by ethomson** [comment] 2020-06-15 09:59
The 1.2.3 release does not work with 20.04 - but it looks like the current tip of master will https://github.com/Azure/azure-storage-fuse/issues/395

**Comment by vibhansa-msft** [comment] 2020-06-15 10:22
As @ethomson mentioned, support for 20.04 is not present in 1.2.3 version. However its present in the master so you can try out tip of master. Also make sure you have required permissions for the mount point and temp directory.

**Comment by techsaau** [comment] 2020-06-15 12:21
@ethomson I have tried with 18.04 version as well. It has same behavior.

**Comment by NaraVen** [comment] 2020-06-17 16:04
Azure Container Instance does not allow host level interaction. So, what you are trying may not be possible. When we use docker with blobfuse for example we have to use docker run --privileged --cap-add=SYS_ADMIN. Azure container Instance never allows privileged mode by design.

**Comment by NaraVen** [comment] 2020-06-17 16:05
This being an Azurt Container Instance feature/ restriction and not blobfuse I am closing this one.

**Closed by NaraVen** 2020-06-17 16:05 UTC
