### ISSUE TITLE
gsutil rsync copies forever when target is blobfuse mount

### ISSUE THREAD

**Issue by e271828-** [Azure/azure-storage-fuse#162] opened 2018-04-09 00:35 UTC
`gsutil -m rsync -d -r gs://export /mnt/blobfuse` running forever is what caused us to notice this. 

`gsutil cp` to copy the same file twice correctly returns "Download already complete for /mnt/blobfuse/file, skipping download but will run integrity checks" while rsync appears to re-copy forever.

Perhaps a filesystem call is unimplemented or partially implemented on blobfuse?  

`ls` gives correct results, but `du` returns zero size for blobfuse mounts. Tested on ubuntu 17.10, blobfuse 1.0.0-RC-preview, gsutil 4.30.

Have opened https://github.com/GoogleCloudPlatform/gsutil/issues/513 as well, as I suspect patching both sides of this is the correct approach.

**Comment by seguler** [comment] 2018-04-09 20:27
So have you tested rsync from local filesystem to blobfuse ? In my tests this just works fine.

I do however suspect the issue is still on blobfuse. Blobfuse does not implement all APIs. In this case, I suspect statfs causing the issue (du). For Statfs, we only return the local cache folder's statistics. Because it is not very easy to calculate object storage stats with one API, which is trivial in file systems. Hence we left this API incomplete in blobfuse...

Regardless - can you enable blobfuse logs and share us the logs ?

**Comment by e271828-** [comment] 2018-04-09 21:38
@seguler We've not tested that, as our use case was shipping many TBs across from GCS to Azure. We've shifted to a different approach for the moment, but this should be easy to replicate.

**Comment by seguler** [comment] 2018-04-09 21:47
@e271828- may I learn what your new approach is ? I know Azure Data Factory, and @Azure/blobporter has this capability too - I was wondering what the best approach came down to.

**Comment by e271828-** [comment] 2018-04-09 22:05
@seguler unfortunately, none of the Azure options we've tried support Google's cloud very well. ADF is what we examined first, but it's not practical when e.g. pulling tens of TBs from BigQuery partitioned tables. blobporter also doesn't support GCS.  For large transfers we use internal tools, which we were hoping to simplify with blobfuse.

**Comment by giventocode** [comment] 2018-04-10 00:01
@e271828 just one clarification, blobporter supports GCP as a source if the S3 compatibility is enabled as described here: https://cloud.google.com/storage/docs/migrating#migration-simple.

**Comment by e271828-** [comment] 2018-04-10 00:31
@giventocode that's a good point, should probably be noted in the README for blobporter. Have you tried it with large numbers of files (>100K) in a bucket?

**Comment by giventocode** [comment] 2018-04-10 00:46
For a large number of files, you can enable the resume option to recover in case of failure and get a list of files transferred when the transfer finishes for confirmation/validation.  Also increasing the batch size, will be helpful (e.g. 5000). 
Thanks for the suggestion, I agree, this should be noted explicitly in the docs.

**Comment by seguler** [comment] 2018-06-30 20:33
Closing this as you've found another solution.

**Closed by seguler** 2018-06-30 20:33 UTC
