### ISSUE TITLE
can't cd the directory pvc mount issue

### ISSUE THREAD

**Issue by zhangchl007** [Azure/azure-storage-fuse#1385] opened 2024-04-09 10:24 UTC
### Which version of blobfuse was used?
blobfuse2

### Which OS distribution and version are you using?

Azure Linux
### If relevant, please share your mount command.
mount by storage class

kubectl  get sc azureblob-fuse-premium-dolphin -o yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2024-04-01T09:02:45Z"
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: azureblob-fuse-premium-dolphin
  resourceVersion: "2873398778"
  uid: c26282f6-21a6-4895-8fc1-b5ed41d379da
mountOptions:
- -o allow_other
- --file-cache-timeout-in-seconds=120
- --use-attr-cache=true
- --cancel-list-on-mount-seconds=10
- -o attr_timeout=120
- -o entry_timeout=120
- -o negative_timeout=120
- --log-level=LOG_WARNING
- --cache-size-mb=1000
parameters:
  skuName: Premium_LRS
  storageAccount: usp1blobprod1abcdolphin
provisioner: blob.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate

### What was the issue encountered?

can't cd the directory pvc mount issue
 
### Have you found a mitigation/solution?

delete pod and remount pvc with another pod

### Please share logs if available.

# abnormal pod
![image](https://github.com/Azure/azure-storage-fuse/assets/13577471/180523d8-9509-4e8b-8feb-bad598f7aabd)

# normal pod
![image](https://github.com/Azure/azure-storage-fuse/assets/13577471/ed301050-f30c-4398-bf55-3294fa1f90b0)

**Comment by souravgupta-msft** [comment] 2024-04-09 11:08
HI @zhangchl007. Can you share if the storage account is HNS enabled or not?
Also please share the PV and PVC config.

**Comment by zhangchl007** [comment] 2024-04-12 01:00
@vibhansa-msft  it is probably a AKS version issue, CX mentioned the pod was schedule on the nodepool with 1.24. the issue was fixed after pod recreation on the nodepool with 1.26.

**Comment by souravgupta-msft** [comment] 2024-04-12 06:46
Thanks for the update. Closing this as the issue is resolved.

**Closed by souravgupta-msft** 2024-04-12 06:46 UTC
Labels: V2
