### ISSUE TITLE
Blobfuse2 performance - HNS vs non-HNS

### ISSUE THREAD

**Issue by mortenjoenby** [Azure/azure-storage-fuse#1046] opened 2023-01-30 12:40 UTC
### Which version of blobfuse was used?
Blobfuse 2.0.1

### Which OS distribution and version are you using?
Oracle Linux 8.4

### If relevant, please share your mount command.
Mounted on pod using AKS 1.24.3, CSI driver 1.19.0.

### What was the issue encountered?
On the back of https://github.com/Azure/azure-storage-fuse/issues/1027, we have now done some performance testing of blob write/copy/move on non-HNS vs. HNS Blob storage account.

### Have you found a mitigation/solution?
No

### Tests ###
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<body link="#0563C1" vlink="#954F72">
operation | blobfuse2 fos | datalake fos

write 100KB | 44,14 | 125,13
read 100KB | 10,16 | 12,20
copy 100KB | 58,30 | 203,90
move 100KB | 56,45 | 207,13
write 1000KB | 81,00 | 163,44
read 1000KB | 27,69 | 32,93
copy 1000KB | 75,23 | 222,89
move 1000KB | 52,17 | 189,32
write 10.000KB | 431,50 | 444,85
read 10.000KB | 171,50 | 197,65
copy 10.000KB | 195,03 | 260,95
move 10.000KB | 46,50 | 150,30
write 100.000KB (100MB) | 4045,90 | 3927,95
read 100.000KB | 1201,40 | 1360,20
copy 100.000KB | 1740,80 | 1698,65
move 100.000KB | 40,60 | 118,10
write 1.000.000KB (1GB) | 32643,75 | 32500,20
read 1.000.000KB | 11086,75 | 11345,10
copy 1.000.000KB | 22179,10 | 20880,00
move 1.000.000KB | 955,20 | 665,65
</body>
</html>

**Comment by mortenjoenby** [comment] 2023-01-30 12:44
@vibhansa-msft / @gapra-msft .
As you see we have run some tests and performance of HNS storage account is (much) worse than non-HNS, at least until file size is above 100MB.
"fos" means FileOutputStream, which is how the files are written.

**Comment by mortenjoenby** [comment] 2023-01-30 12:44
Java code being used:

```private void testWrite() throws IOException {    if (useFileOutputStream) {        try (FileOutputStream outputStream = new FileOutputStream(testFile.toFile())) {            for (int i = 0; i < fileSizeInKiloBytes; i++) {                outputStream.write(oneKiloByte.getBytes());            }        }    } else {        for (int i = 0; i < fileSizeInKiloBytes; i++) {            Files.write(testFile, oneKiloByte.getBytes(), StandardOpenOption.APPEND);        }    }}private void testRead() throws IOException {    try (BufferedReader reader = new BufferedReader(new FileReader(testFile.toFile()))) {        reader.lines().forEach(line -> {            return;        });    }}private void testCopy() throws IOException {    Files.copy(testFile, copiedFile, StandardCopyOption.REPLACE_EXISTING);}private void testMove() throws IOException {    Files.move(testFile, movedFile, StandardCopyOption.REPLACE_EXISTING);}```

**Comment by vibhansa-msft** [comment] 2023-01-31 06:08
HNS accounts are by design a little low on performance compared to non-HNS accounts as they have host of features. In case of blobfuse2 we need to get the properties of a file and to do that we at times need to make two calls to storage this also adds to network latencies. Can you share pipeline and mount command so that I can suggest any config changes for perf improvements, if required.

**Comment by vibhansa-msft** [comment] 2023-01-31 06:11
Can you also validate you have libfuse 3.x compatible system or not. To check execute "fusermount --v" on your shell. If this does not return back error, then you are on libfuse 2.x compliant system. Blobfuse2 has perf improvements done over fuse3 (which is the latest libfuse offering).

**Comment by mortenjoenby** [comment] 2023-02-01 09:46
Hi @vibhansa-msft.
Thanks for the feedback. We were not aware of this overhead with HNS. I don't think that's described anywhere.
Mount options are the same as with non-HNS - so what I wrote here: https://github.com/Azure/azure-storage-fuse/issues/1026#issuecomment-1375359943.

And as mentioned earlier - which was also a surprise - we are using libfuse 2.x as we are on Kubernetes 1.24.3, which only supports Ubuntu 18.04. We have plans for upgrading to Kubernetes 1.26.x beginning of April (skipping 1.25.x). So I have not chance of trying it right now. Of course I could do on a VM, so using the outside AKS.

But ... I assume the difference between non-HNS and HNS will be more or less identical? Performance have improved (based on your tests at least), but that will improve both - right?

**Comment by mortenjoenby** [comment] 2023-02-01 09:52
> HNS accounts are by design a little low on performance compared to non-HNS accounts as they have host of features. In case of blobfuse2 we need to get the properties of a file and to do that we at times need to make two calls to storage this also adds to network latencies. Can you share pipeline and mount command so that I can suggest any config changes for perf improvements, if required.

Right now, I don't think we are ready to take this penalty when using HNS. Any plans of improving this performance?

**Comment by vibhansa-msft** [comment] 2023-02-01 09:57
We have no plans to improve or make any change in blobfuse legacy code. Also, latest Linux distros are fuse3 compliant and fuse3 has bunch of features that can be utilized for improved performance. Looking at fuse3 being the future we have invested more on fuse3 optimizations and features. HNS vs non-HNS performance difference coming from backend will remain the same in either case but fuse3 features that we use kind of compensate that and gives you better performance.
Can you share your mount command and config file. Let me have a look at that and see if we can tune something.

**Comment by mortenjoenby** [comment] 2023-02-01 10:02
@vibhansa-msft , I do not expect improvements to blobfuse (v1)! I fully understand that Blobfuse2 is the focus - and with fuse3. You should align the naming btw :) It's confusing.
Reg. the mount options, I provided you with the link - https://github.com/Azure/azure-storage-fuse/issues/1026#issuecomment-1375359943.

**Comment by mortenjoenby** [comment] 2023-02-01 10:36
Not issues - or rather things that are not working. The reason for this issue was the performance difference of non-HNS vs. HNS.
Now we know that there's a performance overhead of HNS. I think we can close this issue unless you have some configuration changes you want to suggest?
Once we have the chance to use fuse3, we will test again.

**Comment by vibhansa-msft** [comment] 2023-02-01 11:24
If you share your config file and cli I can have a look.

**Comment by vibhansa-msft** [comment] 2023-02-01 11:26
I guess in case of AKS there is no concept of config file and all goes in as cli param only. 
`mountflags [-o default_permissions -o allow_other -o umask=007]
mountOptions [-o default_permissions -o allow_other -o umask=007 --pre-mount-validate=true --use-https=true --cancel-list-on-mount-seconds=10 --empty-dir-check=false --tmp-path=/mnt/testk8sdev1-perftest01-blob2 --container-name=background-processarea-blobv2]`
If this is what you are using then I guess there is nothing much we can change.

**Comment by mortenjoenby** [comment] 2023-02-01 11:47
Thanks @vibhansa-msft .
I am closing this issue for now.

**Comment by mortenjoenby** [comment] 2023-06-02 12:55
Hi @vibhansa-msft / @andyzhangx .
We are on k8s v1.25.6 now, but we seem to be running with CSI Driver 1.19.5 and still fuse2.
fusermount3 command is not recognized either.
And yes, running Ubuntu 22.04 (5.15.0-1035).
Any idea what we might be doing wrong?

**Comment by andyzhangx** [comment] 2023-06-02 14:13
@mortenjoenby `INSTALL_BLOBFUSE: false` means when the blob csi driver is running, it won't install `BLOBFUSE_VERSION: 1.4.4`, if it's `INSTALL_BLOBFUSE: true` then it would install  `BLOBFUSE_VERSION: 1.4.4`, the aks managed blob csi driver is using blobfuse-proxy which runs as a process inside VM, you could just check the blobfuse2 version on the VM, whether it's using `fusermount3`

**Comment by mortenjoenby** [comment] 2023-06-02 14:46
Thanks @andyzhangx .
Perhaps we managed to confuse ourselves. 
I do believe though that we still need to specify "protocol: fuse3" in the Persistent Volume.

**Comment by andyzhangx** [comment] 2023-06-02 15:02
there is no `protocol: fuse3`, and on AKS 1.25 or above version, you don't need to set `protocol: xxx` parameter since it would use Ubuntu 22.04 only supports blobfuse2 mount.

**Comment by vibhansa-msft** [comment] 2023-06-04 07:21
If this config issue is sorted out, can we close this item from here.

**Comment by mortenjoenby** [comment] 2023-06-14 12:42
Hi @vibhansa-msft .
You're saying the "protocol: fuse3" doesn't exist, but we have set it and it's at least accepted.
When looking at https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/driver-parameters.md, it says that protocol defaults to "fuse". Is that then accurate?
It also says that blobfuse2 is still in preview ...!?

And why does the CSI driver version say "1.19.5" when doing a describe on the "blob.csi.azure.com" driver? Shouldn't it be 1.22 or something?

**Comment by mortenjoenby** [comment] 2023-06-14 13:39
@andyzhangx / @vibhansa-msft ,
perhaps v1.19.5 is the latest supported by AKS? Is this page AKS or upstream Kubernetes?
https://github.com/kubernetes-sigs/blob-csi-driver

**Comment by andyzhangx** [comment] 2023-06-14 13:52
> @andyzhangx / @vibhansa-msft , perhaps v1.19.5 is the latest supported by AKS? Is this page AKS or upstream Kubernetes? https://github.com/kubernetes-sigs/blob-csi-driver

@mortenjoenby blob csi driver version is v1.19.5 on AKS 1.24 & 1.25, it's v1.21.3 on AKS 1.26, and blobfuse2 is already GA, I have updated the doc. No matter what `protocol: fusex` you set on AKS 1.25 or above version, the backend would use blobfuse2 mount.

**Comment by mortenjoenby** [comment] 2023-06-15 12:14
Thanks @andyzhangx .
Good to know. Isn't there a place to look these things up?

Some of the previous file tests we did - write, read, copy, move - of different filesizes (100KB, 1000KB, 10,000KB, 100,000KB and 1GB) seems to perform worse than on AKS 1.24 (Ubuntu 18.04). I don't quite understand, but I can re-open that other issue again.
But that was in https://github.com/Azure/azure-storage-fuse/issues/1026, which was comparing Blobfuse v1 vs v2.

Better to create a new issue then I guess? 

But handling smaller files seems worse. Larger files are better.
And the Java app can use both File.write() and FileOutputStream. The latter being much faster.

**Comment by andyzhangx** [comment] 2023-06-15 13:19
> Thanks @andyzhangx . Good to know. Isn't there a place to look these things up?
> 
> Some of the previous file tests we did - write, read, copy, move - of different filesizes (100KB, 1000KB, 10,000KB, 100,000KB and 1GB) seems to perform worse than on AKS 1.24 (Ubuntu 18.04). I don't quite understand, but I can re-open that other issue again. But that was in #1026, which was comparing Blobfuse v1 vs v2.
> 
> Better to create a new issue then I guess?
> 
> But handling smaller files seems worse. Larger files are better. And the Java app can use both File.write() and FileOutputStream. The latter being much faster.

@mortenjoenby you could refer to https://github.com/Azure/AKS/releases for blob csi driver version by searching `blob`.
And about blobfuse v1 & v2 perf issue, I think you could track existing issue or create new issue in this repo.

**Comment by vibhansa-msft** [comment] 2023-08-14 05:21
Closing this as there is no open action item on blobfuse end. Feel free to reopen if there is blobfuse specific ask here.

**Closed by vibhansa-msft** 2023-08-14 05:21 UTC
Labels: V2, performance
