### ISSUE TITLE
AKS blobfuse process will not use the updated SAS token in secret until it is killed.

### ISSUE THREAD

**Issue by henryzhan2022** [Azure/azure-storage-fuse#1301] opened 2023-12-28 20:52 UTC
### Which version of blobfuse was used?
1.4.5

### Which OS distribution and version are you using?
Ubuntu 18.04.6 LTS

### If relevant, please share your mount command.
Blobfuse mounted with this procedure.
https://learn.microsoft.com/en-us/azure/aks/azure-csi-blob-storage-provision?tabs=mount-blobfuse%2Csecret#mount-volume

### What was the issue encountered?
When SAS token was about to expire, CX use kubectl to update the token stored in secret.
After old SAS token expired, the blobfuse process was still using the staled one and get 403 as a result.
![image](https://github.com/Azure/azure-storage-fuse/assets/110992699/e9b03b02-6bd6-470b-91c4-3a3cdd83717d)

### Have you found a mitigation/solution?
To mitigate the issue, CX had to stop all the PODs running on the node with blobfuse in use to let blobfuse process terminate and then restart the PODs.

**Comment by vibhansa-msft** [comment] 2023-12-29 04:58
This is by design, if the SAS expires during the course of mount blobfuse will not unmount on its own. This is a file system driver mounted explicitly by the user and has to be unmounted explicitly by user only. Also, you are using a very old version of blobfuse, kindly upgrade to latest blobfuse 2.x version. We do have a feature in 2.x where you can change the SAS token on the flly but that will require a config file to be used and in AKS scenario generally PV mount is done using all cli params. You can try the config file based stuff if possible and when SAS token expires you just need to update the config file with the latest token.
Closing this report here as expiry of SAS token can not trigger unmount, it has to be done explicitly by user only.

**Closed by vibhansa-msft** 2023-12-29 04:58 UTC

**Comment by henryzhan2022** [comment] 2023-12-29 17:46
@vibhansa-msft Thank you for the quick help here. Much appreciated.

Hi @andyzhangx I checked this thread and it appears AKS should use blobfuse2 with managed csi driver.
https://github.com/Azure/azure-storage-fuse/issues/1289

The CX is in Mooncake and it appears the version is 1.4.5. Could you help me reconfirm if indeed this is using v1?
![image](https://github.com/Azure/azure-storage-fuse/assets/110992699/20ea4ae4-444d-4fe1-b2d9-c799c2cf312d)

How we can upgrade to v1 and configure config file to utilize the SAS token change on the fly feature?

Thank you.

**Comment by andyzhangx** [comment] 2023-12-30 04:05
> @vibhansa-msft Thank you for the quick help here. Much appreciated.
> 
> Hi @andyzhangx I checked this thread and it appears AKS should use blobfuse2 with managed csi driver. #1289
> 
> The CX is in Mooncake and it appears the version is 1.4.5. Could you help me reconfirm if indeed this is using v1? ![image](https://private-user-images.githubusercontent.com/110992699/293404345-20ea4ae4-444d-4fe1-b2d9-c799c2cf312d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MDkyODksIm5iZiI6MTcwMzkwODk4OSwicGF0aCI6Ii8xMTA5OTI2OTkvMjkzNDA0MzQ1LTIwZWE0YWU0LTQ0NGQtNGZlMS1iMmQ5LWM3OTljMmNmMzEyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMFQwNDAzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTgzYWE5OWIwY2Y5MWVlNTY1YjUwODBiMjBlZjA2MTE0Y2M1MGViYzMwMGU0ZjlhZmNjNzcyMjAwODc1MWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hRilDwpgyIFeJ3lIVb3hFBYM6arTFWHcfqs7aWbKpA4) ![image](https://private-user-images.githubusercontent.com/110992699/293404781-4b273e61-167f-4536-8342-777150f36665.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MDkyODksIm5iZiI6MTcwMzkwODk4OSwicGF0aCI6Ii8xMTA5OTI2OTkvMjkzNDA0NzgxLTRiMjczZTYxLTE2N2YtNDUzNi04MzQyLTc3NzE1MGYzNjY2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMFQwNDAzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDVmYzRlY2M5ZWJiNzZjYjg3OTAzMDUzNDg2ZjI2NzA5ODY5NTljZWE4OGU0ZmI1NGRmMGVjZWRlY2UwZWYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ofsmPAcJKOqRmANRhaxJePrcA1HySevbvGJWWGTDZKs)
> 
> How we can upgrade to v2 and make use of the config file to utilize the SAS token change on the fly feature?
> 
> Thank you.

@henryzhan2022 if you are using the managed blob csi driver on AKS, and with AKS 1.25 or later version, the driver is already using blobfuse2 by default.

**Comment by henryzhan2022** [comment] 2024-01-02 17:19
> @henryzhan2022 if you are using the managed blob csi driver on AKS, and with AKS 1.25 or later version, the driver is already using blobfuse2 by default.

Thanks @andyzhangx . 

CX is running 1.23. If they upgrade to 1.25, are they going to use v2 automatically?

How to setup config file in AKS after upgrade?

**Comment by andyzhangx** [comment] 2024-01-03 03:09
> > @henryzhan2022 if you are using the managed blob csi driver on AKS, and with AKS 1.25 or later version, the driver is already using blobfuse2 by default.
> 
> Thanks @andyzhangx .
> 
> CX is running 1.23. If they upgrade to 1.25, are they going to use v2 automatically?
> 
> How to setup config file in AKS after upgrade?

@henryzhan2022 yes, after upgrading to AKS 1.25, blob csi driver would use v2 automatically, it's not necessary to make any config change after upgrade.
