### ISSUE TITLE
Blobfuse cannot mount a folder and file in the same folder with the same name

### ISSUE THREAD

**Issue by zoekdestep** [Azure/azure-storage-fuse#335] opened 2019-12-03 10:12 UTC
### Which version of the blobfuse was used?
Blobfuse 1.0.3

### Which OS (please include version) are you using?
LSB Version:    core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

### What problem was encountered?
**Topic:** Blobfuse cannot mount a folder and file in the same folder with the same name.

This was brought to my attention by my customer, and I repro'd it. Both showed different but undesirable behavior. The customer uses blobfuse with Azure ML.

**From the customer:**
We recently observed the following behavior:

In Azure blob storage, one can create two blobs like this:
Blob 1: /containername/foldername/file.txt
Blob 2: /containername/foldername
The second blob is a non-empty file (non-emptiness is important, otherwise the behavior does not occur)
Blobfuse cannot mount this properly as a POSIX file system cannot have a folder and file in the same folder with same name. Instead blobfuse makes the blob 2 available, but blob 1 is missing.

Questions:
- Can blobfuse (and with that AML) be parameterized to use a “depth-first” mounting, i.e. in my example Blob 1 would be present but Blob 2 would be missing?
- Is there a convenient way to find such “conflicts”? Ideally we would disallow such constellations on the storage-account level. If not possible, we could raise an Alarm whenever this occurs/run an ADO pipeline that searches for these constellations regularly

**Repro:**
When reproing, I don't get the exact same behavior but still undesirable. In the case of the customer, only one file got mounted - in my case, the same-named folder and file got mounted two times as a file (as opposed to desired behavior, one time as folder and one time as file). Test-folder 'anothername' mounts properly as folder. Let me know if you want the exact repro code.

### Have you found a mitigation/solution?
No.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
Not relevant.

### If relevant, please share your mount command.
`sudo blobfuse ~/mycontainer --tmp-path=/mnt/resource/blobfusetmp --config-file=/home/zoekdestep/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120
`

**Comment by adreed-msft** [comment] 2019-12-03 21:23
Files and folders can't share the same names in an actual filesystem, contrary to how Blob storage works.

Blob Storage has no clue that folders even exist to start with, and treats the folders as a part of a blob's name.

As a mitigation, you could rename the conflicting blob's name to be able to access both.

**Comment by zoekdestep** [comment] 2019-12-06 15:44
Hi,

Thanks for your comment. I understand the mitigation, but in large-scale enterprise project sometimes a name is being changed accidentally and the system breaks. 

Therefore, the questions remain: 
- Can blobfuse (and with that AML) be parameterized to use a “depth-first” mounting, i.e. in my example Blob 1 would be present but Blob 2 would be missing?
- Is there a convenient way to find such “conflicts”?

Thanks.

**Comment by amnguye** [comment] 2019-12-09 21:39
Hi,

Blobfuse cannot be parameterized to use a "depth-first" mounting.

It would be difficult to find such conflicts, as mentioned previously, files and folders can't share the same names in a filesystem. A filesystem would not mention any conflict due to the nature of it defaulting to rewriting.

**Comment by xinyi-joffre** [comment] 2020-01-16 19:29
I also ran into this with a customer--it would be great to have a way to ignore these dummy files, since they are commonly generated by many other services (Spark, HDInsight, Azure Data Factory, etc.). Without a fix for this, Azure ML mounting does not work as intended for many big data scenarios where files are put in subdirectories (such as parquet).

**Comment by algattik** [comment] 2020-03-10 07:11
The size-zero blobs in question have the `hdi_isfolder` metadata item set to `true`.
https://github.com/apache/hadoop/blob/a55d6bba71c81c1c4e9d8cd11f55c78f10a548b0/hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azure/TestBlobMetadata.java#L255

So the fix might be for blobfuse to ignore blobs with that metadata set.

**Comment by algattik** [comment] 2020-03-12 17:49
It seems the behavior in question is actually implemented: https://github.com/Azure/azure-storage-fuse/blob/4e101176567b81403d4527e31226c42bf5d52e4e/blobfuse/utilities.cpp#L214

As the hadoop client library sets the `hdi_isfolder` flag, blobfuse should work with the output of jobs using hadoop client (e.g. Databricks)

**Comment by NaraVen** [comment] 2020-06-18 17:12
So, let me try to understand your requirement.
In Azure blob storage, one can create two blobs like this:
Blob 1: /containername/foldername/file.txt
Blob 2: /containername/foldername ( non empty file not zero blob)

If Blob1 is present meaning there is a directory with the same name  and it is non-empty all the files in the directory should be displayed and it is ok to ignore Blob2. However if the directory is empty then Blob2 should be ignored and Blob1 should be displayed if it is non-empty.

**Comment by NaraVen** [comment] 2020-06-18 17:13
> It seems the behavior in question is actually implemented:
> 
> https://github.com/Azure/azure-storage-fuse/blob/4e101176567b81403d4527e31226c42bf5d52e4e/blobfuse/utilities.cpp#L214
> 
> As the hadoop client library sets the `hdi_isfolder` flag, blobfuse should work with the output of jobs using hadoop client (e.g. Databricks)

Blobfuse already uses this and I want to call out that for empty blobs of zero size you won't see any issues, this issue only shows up when the blob is non-empty.

**Closed** 2020-10-06 21:14 UTC
Labels: triaged
