### ISSUE TITLE
The speed of data upload/download to Azure storage by blobfuse mount point randomly a bit long from some small size file 

### ISSUE THREAD

**Issue by Vi-2022** [Azure/azure-storage-fuse#895] opened 2022-09-08 09:15 UTC
### Which version of the blobfuse was used?
blobfuse-1.4.5

### Which OS (please include version) are you using?
Linux

### What problem was encountered?
According to recent watching, we can see data upload/download to Azure’s Storage Pool by blobfuse mount point looks complete, but the issue is transfer speed randomly a bit long from some small size file

### Have you found a mitigation/solution?
No, according to the blobfuse readme, I set "-file-cache-timeout-in-seconds=0" and increase the space of "--tmp-path", but no improve performance.

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
2022-08-25T03:35:01.693492+00:00 cn-hi Ig blobfuse [20931]: Successfully created file /xxxx/ADCAM_70B267515_20190405_075723_bus_0254-9004.MF4.0000067604 i
n file cache.
2022-08-25T03:35:16.904995+00:00 cn-hi1g blobfuse [20931] : successfully uploaded file /xxxx/ADCAM_70B267515_20190405_075723_bus_0254-9004.MF4.0000067604
to blob xxxx/ADCAM_70B267515_20190405
L075723_bus_0254-9004.MF4.0000067604.
2022-08-25T03:35:16.927029+00:00 cn-hilg blobfuse [20931] : Successfully called start_copy from blob xxxx/ADCAM_70B267515_20190405_075723_bus_0254-9004.MF
4.0000067604 to blob xxxx/ADCAM_70B26 7515_20190405_075723_bus_0254-9004.MF4
2022-08-25T03:35:16.938324+00:00 cn-hi1g bTobfuse [20931] : copy operation from xxxx/ADCAM_70B267515_20190405_075723_bus_0254-9004.MF4.0000067604 to xxxx/ADCAM_70B267515_20190405_075723_bus_0
254-9004.MF4 succeeded.
2022-08-25T03:35:16.953513+00:00 cn-hilg blobfuse [20931]: Successfully deleted source blob xxxx/ADCAM_70B267515_20190405_075723_bus_0254-9004.MF4.000006
7604 during rename operation.
2022-08-25T03:35:16.954177+00:00 cn-hi 1g cn-hilg nginx: - /2-sim/BCT/xxxx/ADCAM_70B267515_20190405_075723_bus_0254-9004.MF4 - - 10.123.11.123 - [25/A
ug/2022:03:35:16 +0000] "PUT /2-Sim/BCT/xxxx/
ADCAM_70в267515_20190405_075723_bus_0254-9004.MF4 HTTP/1.0" 201 transfered=0 request_time=15.302 2022-08-25T03:35:16.978140+00:00 cn-hi1g blobfuse [20931]: Successfully created file /xxxx/ADCAM_70B267515_20190405_075723_deb_0254-9004.MF4.0000067606 i
n file cache.

**Comment by vibhansa-msft** [comment] 2022-09-08 10:13
"-file-cache-timeout-in-seconds=0" or increasing size of "--tmp-path" does not impact much into download/upload performance. They are options to control your local cache in terms of size and how long a file is valid in local cache.
As you keep file-cache-timeout-in-seconds as '0' it means as soon as application closes the file-handle it will be deleted from the local cache. In case you application might reopen the file immediately; it will be better to keep this number little high so that blobfuse does not end up downloading the file again which is just uploaded. 

If you are observing issues more with respect to the upload/download performance, then you can give our next generation blobfuse aka "blobfuse2" a try which is in preview mode as of now. preview.3 binaries are available in release section of this GitHub repo as well as Linux repos are also updated for the same. If has improvements both in terms of features and performance.

**Comment by vibhansa-msft** [comment] 2022-09-12 08:43
Kindly update you were able to try out blobfuse2 or not, or if you need any assistance on this.

**Comment by huanghaiqing1** [comment] 2022-09-13 03:19
Hello, we are unable to upgrade to a preview version based on blobfuse2, since our business needs to base on a stable blobfuse version. If you can open some debug settings and confirm it's a known-issue in blobfuse 1.4.5 and can't give any fix. And blobfuse2 solve this issue, we can show to our business unit and give next plan. From Azure support uploaded log, you can see the major time coset happened between Successfully created file cache and successfully uploaded file. Since our blobfuse mountpoint is based on a 40Gb special line and the sar/paping testing is ok. The transfered file is 10-30M size and only one time usage, so if you can help showing more detail debug level log info between this stage can guide us what really happened for the unexpected and sudden slow. Currently the cases happens as a rate of 0.3% and randemly.

**Comment by Vi-2022** [comment] 2022-09-13 03:27
@vibhansa-msft , please see above @huanghaiqing1 's reply, and assistance on it , thanks .

**Comment by vibhansa-msft** [comment] 2022-09-13 09:30
"Between Successfully created file cache and successfully uploaded file." : These 2 items points to time when file was created by application and when it was uploaded. So in between there shall be lot of read/write operations going on with this file. Also, blobfuse will not upload the file to container until its closed by application. For some reason if application holds onto open handle, you will see lag in uploading the data.
For the other part about logging, while mounting blobfuse you can provide cli parameter "--log-level=LOG_DEBUG" and collect the log file while your test is in progress. Post the issue is hit share the log file and let me know the filename which you observed was slow in upload/download. We can dig logs around that file and see if we can route-cause this.
"blobfuse2" is written from scratch and even tech is different compared to legacy blobfuse. It has better performance and features. So here it's not about a known issue in v1 with respect to performance that v2 counters but in general v2 is better than v1. If you can just give it a try and see that is performs better, you will have reasons to migrate once its GA (which shall be by the end of this calendar year).

**Comment by huanghaiqing1** [comment] 2022-09-16 09:06
[](url)I have a question, when I enable blobfuse moint with debug mode open, but from messages log, it shows logging level is “LOG_WARNING”, does it match? We hope by set some parameters in blobfuse parameter, we can see which app as gitlab said is holding the blobfuse file in blobfuse caching status. Thanks.

blobfuse /HPCC/$5_$containerName --log-level=LOG_DEBUG --tmp-path=/tmp/ramdisk --config-file=$Azure_cfg_PATH --file-cache-timeout-in-seconds=0 --max-concurrency=20 --invalidate-on-sync==true -o ro -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other -o none
![aaa](https://user-images.githubusercontent.com/30017444/190600965-e165ea5e-2576-4889-8361-0b301b483914.jpg)
mpty

**Comment by vibhansa-msft** [comment] 2022-09-16 09:44
"--log-level=LOG_DEBUG" should have set logging level to debug mode.
"which app as gitlab said is holding the blobfuse file in blobfuse caching status" : this is not possible. Blobfuse does not track which application has requested for opening a file, or holding an open handle. You need to check this part in your application only.

**Comment by vibhansa-msft** [comment] 2022-09-20 05:46
Can you provide requested inputs if the problem persists.

**Comment by Vi-2022** [comment] 2022-09-20 06:24
@huanghaiqing1 , could you please help to provide the inputs ?

**Comment by huanghaiqing1** [comment] 2022-09-21 06:59
Based on your feedback, I can't input more, since our business can't switch to blobfuse2 with any unknown risk. And you insist on app will hold the cache file and DEBUG-MODE doesn't show any detail info about APPs. So I can't comment on anything else here. And since the case is opened by Azure China support, becuase our business is depending on their storage system and using blobfuse techincal, so I think it should goes to Azure to decide close the case here or not.

**Comment by Vi-2022** [comment] 2022-09-26 02:09
@vibhansa-msft , the inputs has been provided before.
blobfuse /HPCC/$5_$containerName --log-level=LOG_DEBUG --tmp-path=/tmp/ramdisk --config-file=$Azure_cfg_PATH --file-cache-timeout-in-seconds=0 --max-concurrency=20 --invalidate-on-sync==true -o ro -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other -o none

And after run above command, the message is as following :
![image](https://user-images.githubusercontent.com/112463870/192180155-1a53b064-b503-46d9-b9e0-ebdb6675282a.png)

**Comment by vibhansa-msft** [comment] 2022-09-26 04:20
Can you try with below command and see if we get debug level logs :
"blobfuse /HPCC/$5_$containerName --tmp-path=/tmp/ramdisk --config-file=$Azure_cfg_PATH  --log-level=LOG_DEBUG --file-cache-timeout-in-seconds=0 --invalidate-on-sync=true -o ro -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other"

**Comment by vibhansa-msft** [comment] 2022-09-26 04:24
For your other comments regarding caching the file : blobfuse will keep a file in cache untill user application closes the handle to that file. Once close is executed, blobfuse adds the file to eviction list and post the given timeout it will be evicted. As you have set the timeout to be 0 it shall be evicted immediately after close (provided there are no other open handles to the same file).
For blobfuse2 (v2) my request is to give it a try and see if it solves your problem or not. I am not asking to deploy it on your production environment right now. If you try v2 and observe any issue we can fix it so that when we do GA (in couple of months), you can start migrating. For v2 do not worry about the support part, though it's in preview mode we are fully supporting it.

**Comment by huanghaiqing1** [comment] 2022-09-28 08:07
Hello, yes currently we focuse on v1 because of our app design. Now I enable blobfuse with debug mode mount: blobfuse /HPCC/$5_$containerName --log-level=LOG_DEBUG --tmp-path=/tmp/ramdisk --config-file=$Azure_cfg_PATH --file-cache-timeout-in-seconds=0 --max-concurrency=20 --invalidate-on-sync=true -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other -o nonempty -o rw

And by set --file-cache-timeout-in-seconds=0 with log-level set as LOG_DEBUG, this time we can see more detail and we will keep on watching, and hope to see more when long time occpution happened during blobfuse from cache to uplaode stage.
<img width="959" alt="Capture1" src="https://user-images.githubusercontent.com/30017444/192724472-652fdef2-ec96-446c-802a-f4852d795713.PNG">
<img width="841" alt="Capture2" src="https://user-images.githubusercontent.com/30017444/192724500-893959d7-eedd-45fd-9ace-f932491425b2.PNG">

**Comment by vibhansa-msft** [comment] 2022-10-04 02:16
Kindly share logs if you were able to reproduce the issue, where blobfuse is taking longer time to upload/download.

**Comment by Vi-2022** [comment] 2022-10-11 03:47
@vibhansa-msft , , looks this time we can see more detail in debug mode, when set --file-cache-timeout-in-seconds=0 together with enable log-debug mode when blobfuse mount. And we will keep on watching. Just one question, in our production system, --file-cache-timeout-in-seconds=1 and required read-only mount, when I can set it as --file-cache-timeout-in-seconds=0 with no additional performance issue with log-debug mode open? Here I also update in below github. If you can confirm it, I can set same as test environment and try to involve users to test and see whether can fetch more detail info in messages.

**Comment by vibhansa-msft** [comment] 2022-10-11 05:09
"--file-cache-timeout-in-seconds=0" is a recommended setting for applications which do not require same file to be open/read multiple times. Local caching is helpful only when you tend to open and read/write file in quick succession. This does not have any performance impact as such, but if application reopens the file within seconds, it will be redownloaded. So, this part totally depends on what is your application behavior.

"--log-level=LOG_DEBUG" is not recommended for production environments, as this is heavy in terms of logging and will have performance impact.

**Comment by vibhansa-msft** [comment] 2022-10-17 08:35
Closing this as there are no open queries on tis thread for now. Feel free to reopen if you have any further queries on this.

**Closed by vibhansa-msft** 2022-10-17 08:35 UTC
Labels: V1
