### ISSUE TITLE
issue while copying large files

### ISSUE THREAD

**Issue by vinulohar007** [Azure/azure-storage-fuse#107] opened 2018-02-22 13:13 UTC
Hi Team,

I am facing an issue while creating large files on mounted blob storage. 

In my scenario I have a blob storage mounted on the SUSE Linux machine and we are having SAP DB. So we are dumping the DB backup directly to the mounted blob storage. Backup size is about 250GB.
We also have a large space in temp file system. When we have started the backup on blob storage files are started to create in temp space but it has not created on blob. we only see 0 byes of files.

Backup is completed in temp space but files not uploaded to blob and mounted blob is seems unmounted.

@seguler 
Can you please help here?

 **# more mount.sh**
#!/bin/bash
BLOBFS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $BLOBFS_DIR/build
./blobfuse $1 --tmp-path=/databck/blobfusetmp -o uid=1004 -o allow_other  -o gid=1001 -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120  --
file-cache-timeout-in-seconds=120 --config-file=../connection.cfg

Do I need to add any parameter here or need to modify any parameter with respect to timeout?

Thanks,
Vinayak lohar

**Comment by seguler** [comment] 2018-02-22 19:25
@asorrin-msft what is the max file size we support ? Is it 200GB at the moment ?

**Comment by seguler** [comment] 2018-02-23 02:59
I just verified. The largest file we support is 200GB. I don't see any reason to push this up to 800GB though... Perhaps we can do this in the next release.

**Comment by vinulohar007** [comment] 2018-02-23 03:12
Hi @seguler,

When can we expect the next release?

Can you please provide the link to the rpm file of blobfuse. 

I have tried to add the Microsoft repo but I have not found the blobfuse rpm there. 


Thanks
Vinayak

**Comment by seguler** [comment] 2018-02-23 03:14
Here is the rpm for rhel 7.3: https://packages.microsoft.com/rhel/7.3/prod/blobfuse-0.2.4-el7.rpm

What is your Linux distro/version ? Let me validate if rpm works for that release.

**Comment by vinulohar007** [comment] 2018-02-23 03:19
We are using suse Linux 12 sp2

**Comment by vinulohar007** [comment] 2018-02-23 03:22
Hi @seguler,

I have just checked blobfuse rpm is not available there in the sles repo

https://packages.microsoft.com/sles/12/prod/


Please help us with the same if available.  

Thanks
Vinayak

**Comment by vinulohar007** [comment] 2018-02-26 11:26
@seguler ,

Any update on the repository ?


Thanks,
Vinayak  Lohar

**Comment by seguler** [comment] 2018-02-26 21:17
I am hoping we'll release the support for 5TB blobs within this week. Stay tuned!

**Comment by seguler** [comment] 2018-02-28 04:15
This is now fixed in the dev branch. Please clone from dev, build and test... Let us know if you encounter any issues

**Comment by vinulohar007** [comment] 2018-02-28 14:52
Hi @seguler ,

We have downloaded the dev code and complied it. We ran the backup of 225GB into the mounted blob. backup is started running, we have seen whenever it is writing in the temp space that time it has written in the blob as well.  But at the end once backup complete the connection has braked and no data is available on the blob. 0 byte files are there. and when we try to list the files from the Linux box in the mounted directory we got  ** ls: cannot open directory '.': Transport endpoint is not connected ** error.

**Comment by seguler** [comment] 2018-02-28 15:45
I'm sorry about that - it looks like it is crashing. Do you have enough space in /databck to store 225gb ? I cannot think of anything else going wrong at the moment

**Comment by vinulohar007** [comment] 2018-02-28 16:13
Hi @seguler 
 I have created space more than 500gb on /databck before starting the operation. 

Thanks,
Vinayak

**Comment by seguler** [comment] 2018-02-28 17:32
Ok - I just realized: this is not a single file that is 225GB ? It consists of 5 files, right ? This should also work in the master branch as well... There is a different issue here..

Are you using the Linux cp command to copy these backup files into blobfuse ? Or is it SAP DB that tries to write to this location ?

Do you mind sharing a full debug log with us here for us to investigate ?
In order to enable logs; you need to:
1. Edit blobfuse/blobfuse.h and set AZS_PRINT to 1
2. Re-compile using ./build.sh
3. Edit mount.sh to pass the debug flag (-f)
```./blobfuse -f $1......```
4. Remount blobfuse and redirect the logs
./mount.sh /path/to/mount &> blobfuse.log
5. Reproduce the issue, and you should have lot of logs saved in blobfuse.log. Please send it over to us.

**Comment by vinulohar007** [comment] 2018-02-28 17:41
Hi @seguler

We are having SAP system, and it's DB (SYBASE) . We are dumping the DB backup directly  to the mounted blob location. We are not using cp command. The DB backup is writing on That 5 files simultaneously.  that consist of 225gb. 

I will follow the steps given above and let you provide the logs by tomorrow once I am in office.


Thanks,
Vinayak

**Comment by seguler** [comment] 2018-10-16 03:18
Closing as no update.

**Closed by seguler** 2018-10-16 03:18 UTC
Labels: enhancement
