### ISSUE TITLE
Question!!! really could use some advice or help.

### ISSUE THREAD

**Issue by lbabay** [Azure/azure-storage-fuse#514] opened 2020-10-16 21:14 UTC
### Which version of the blobfuse was used?
1.2.4

### Which OS (please include version) are you using?

linux ubuntu server 18.04
### What problem was encountered?
This really isnt a problem but I could really use an answer to a question. I have about 500GB of pictures that are going to be written to a directory. If I redirect the pictures to a directory that is backed by a storage container via blobfuse, will that keep the data from being stored locally? or do i need to find another solution that will just keep the data in the cloud and not locally.

### Have you found a mitigation/solution?
NA

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
NA

### If relevant, please share your mount command.
NA

**Comment by vibhansa-msft** [comment] 2020-10-17 08:13
If you redirect your pictures to a directory mounted using Blobfuse, it will upload it to the container. There will not be any local copy maintained, however blobfuse maintains a cache on the local disk/ramdisk and your files will exists in cache till cache expires. You can set cache-expiry time to 0 if you wish to remove them from cache immediately to save disk space.

**Comment by vibhansa-msft** [comment] 2020-10-17 08:16
Closing this as this is not a bug report. Feel free to post your any further queries in this thread.

**Closed by vibhansa-msft** 2020-10-17 08:16 UTC
