### ISSUE TITLE
Streaming write does not working or working unexpectedly

### ISSUE THREAD

**Issue by gurartem** [Azure/azure-storage-fuse#920] opened 2022-09-28 14:00 UTC
### Which version of the blobfuse was used?
blobfuse2 version 2.0.0-preview.3

### Which OS (please include version) are you using?
Debian GNU/Linux 11 (bullseye)

### What problem was encountered?
We have testing streaming write. But any combinations with config files have no effect.
We test files of 500Mb and 150Gb. The cache disk has 2 Tb (Nvme)
As the result, I see incoming traffic increasing and outgoing traffic waiting for the file to be copied to the cache.

*.yaml file looks like this:
`allow-other: true`
`components:`
    `- libfuse`
    `- stream`
    `- file_cache`
    `- attr_cache`
    `- azstorage`
`libfuse:`
    `attribute-expiration-sec: 240`
    `entry-expiration-sec: 240`
    `negative-entry-expiration-sec: 240`

`stream:`
    `blocks-per-file: 3`
    `cache-size-mb: 1024`
    `handle-limit: 1024`

`file_cache:`
    `path: ...`
    `allow-non-empty-temp: true`
    `cleanup-on-start: true`

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
We don't have any errors

### If relevant, please share your mount command.
blobfuse2 mount /opt/blobfuse/container --config_file=/opt/blobfuse/fuse_connection.yaml

**Comment by tasherif-msft** [comment] 2022-09-28 16:03
Hi @gurartem! there has been changes to our stream config parameters. Please refer to https://github.com/Azure/azure-storage-fuse/blob/blobfuse2-2.0.0-preview.3/setup/baseConfig.yaml#L45 to set it up correctly. Basically, the config you currently have outdated parameters leading to `stream-only` mode (no caching - every request hitting Azure). Let me know if it gets fixed after updating your config parameters

**Comment by gurartem** [comment] 2022-09-28 17:22
Hi @tasherif-msft! Thank you for your response.

I don't understand where my mistake is.
At first I only added the `stream` component. Nothing changed. After that I tried to add some parameters to the stream (blocks-per-file and so on). Can you show me how I need to configure the *.yaml file for stream write?

**Comment by tasherif-msft** [comment] 2022-09-28 17:30
Hi! so for your stream component you can have:
```
stream:
  handle-buffer-size-mb: 4
  handle-limit: 1000
  block-size-mb:  1
``` 
I also noticed you `file_cache` in your config - if you wanna do streaming without saving on disk then please remove the file cache component from your pipeline

**Comment by vibhansa-msft** [comment] 2022-10-04 02:10
"Transport endpoint is not connected" points to a situation where blobfuse2 binary has terminated abruptly. Can you validate once you mount these folder are accessible and later when you run your test it fails?
By default logs go to /var/log/syslog. I believe its terminating so if you can collect core dump of the binary it will be great help to understand the root-cause. 
Can you share your config file and mount command again post the changes suggested above.

**Comment by vibhansa-msft** [comment] 2022-10-12 17:20
If the issue is persistent, can you share the requested info.

**Comment by vibhansa-msft** [comment] 2022-10-17 08:33
Closing this as there has been no update from customer end. Feel free to reopen if the issue persists and you have the required info.

**Closed by vibhansa-msft** 2022-10-17 08:33 UTC
Labels: bug, V2
