### ISSUE TITLE
The folders (and the files under the folder) shown correctly on the web interface are shown as unreadable files (repeated for 2 times) after being mounted to a local Linux machine:

### ISSUE THREAD

**Issue by PkuRainBow** [Azure/azure-storage-fuse#889] opened 2022-09-01 06:59 UTC
### Which version of the blobfuse was used?
Note: If you are using blobfuse 1.X.X, we would like to encourage you to try out the next generation of blobfuse, [blobfuse2](https://github.com/Azure/azure-storage-fuse/tree/main) which is currently in preview. The latest preview binaries can be found [here](https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse2-2.0.0-preview2) and more information on how to convert config options can be found [here](https://github.com/Azure/azure-storage-fuse/blob/main/MIGRATION.md#blobfuse-v2-guide-for-mapping-options-from-v1xx-to-v2xx). We will continue to respond to bug reports for blobfuse 1.X.X, however, no more feature requests will be considered.

blobfuse 1.3.6

### Which OS (please include version) are you using?

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

### What problem was encountered?

The folders (and the files under the folder) shown correctly on the web interface are shown as files (repeated for 2 times) after being mounted to a local Linux machine:
 
(screenshot of the web page)
<img width="733" alt="image" src="https://user-images.githubusercontent.com/4639578/187849866-ae2eb80d-8eb8-47ba-b1fe-389878b9c1a3.png">

(screenshot of the mounted path)
<img width="897" alt="image" src="https://user-images.githubusercontent.com/4639578/187849958-e1f83d83-c167-4432-b621-3d35e2b23958.png">

### Have you found a mitigation/solution?

No. 

### If relevant, please share your mount command.

Follow the pipeline summarized in the official document.

https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux

**Comment by vibhansa-msft** [comment] 2022-09-01 07:05
Is this a gen-2 (HNS enabled) account? If so, can you share mount command and config file. To mount gen2 account, you need to provide a cli option while mounting "--use-adls=true".
Also, we do not release blobfuse for ubuntu-16 officially so is this binary your local build or you have installed from some other repo.

**Comment by vibhansa-msft** [comment] 2022-09-01 07:06
Also, as the bug template shows we have the next generation of blobfuse in preview mode, you can give that a try.

**Comment by PkuRainBow** [comment] 2022-09-01 07:08
Thanks for your quick reply. Our account kind is BlockBlobStorage.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/4639578/187853196-92c5730d-3ad0-4129-9b04-13c469cdebcb.png">

**Comment by vibhansa-msft** [comment] 2022-09-01 07:11
This is not showing HNS is enabled or not. From portal on your account select overview tab and you shall see something like this.
![image](https://user-images.githubusercontent.com/64532198/187853830-e75530b9-0133-480d-a4b1-374b2d619234.png)

**Comment by PkuRainBow** [comment] 2022-09-01 07:12
The mount command is 

`sudo blobfuse ./detrscus --tmp-path=/mnt/ramdisk_detrscus/blobfusetmp  --config-file=./connect_detrscus.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other`

**Comment by PkuRainBow** [comment] 2022-09-01 07:13
It seems that HNS is disabled, shown as follows:

<img width="499" alt="image" src="https://user-images.githubusercontent.com/4639578/187854126-73af4153-f4ee-4f33-99e0-cbd7100c2a25.png">

**Comment by vibhansa-msft** [comment] 2022-09-01 07:13
Can you share how these directories were created, for non-HNS account blobfuse needs a special directory marker file and if it's not there blobfuse may not show the listing properly.

**Comment by vibhansa-msft** [comment] 2022-09-01 07:13
for each directory there shall be a 0 byte file in your container having a meta property "hdi_isfolder=true"

**Comment by PkuRainBow** [comment] 2022-09-01 07:16
We use Azure data factory to copy these folders from another storage account (blob) belonging to another subscription. 

https://docs.microsoft.com/en-us/azure/data-factory/quickstart-create-data-factory-copy-data-tool

**Comment by vibhansa-msft** [comment] 2022-09-01 07:18
On portal can you check if there is a 0-byte file for each directory with exactly the same name as folder-name.

**Comment by vibhansa-msft** [comment] 2022-09-01 07:19
You can also give our next generation blobfuse a try and may be it lists the files/folders properly.
https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse2-2.0.0-preview2

**Comment by PkuRainBow** [comment] 2022-09-01 07:19
Yes, there exists a 0-byte file for each directory with exactly the same name as folder name on the web portal.

**Comment by vibhansa-msft** [comment] 2022-09-01 07:22
Can you give blobfuse2 a try on this same setup or try adding "--use-attr-cache=true" in your current mount command and see if you get correct output. If the issue persists, then we will need debug logs of blobfuse to investigate.

**Comment by PkuRainBow** [comment] 2022-09-01 07:27
We meet the following errors when installing the blobfuse2 following the [official document](https://docs.microsoft.com/en-us/azure/storage/blobs/blobfuse2-how-to-deploy):

<img width="583" alt="image" src="https://user-images.githubusercontent.com/4639578/187856615-bc94445b-13fa-4280-ab21-518075cf0195.png">

**Comment by vibhansa-msft** [comment] 2022-09-01 07:31
libfuse3 is supported only on ubuntu-20 onwards, so if you are using ubn-16 or 18 then install blobfuse2 from ubn-18 repo which is fuse2 compliant.

**Comment by PkuRainBow** [comment] 2022-09-01 07:33
It would be great if you could share the link to ubn-18 repo.

**Comment by vibhansa-msft** [comment] 2022-09-01 08:54
https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb

**Comment by vibhansa-msft** [comment] 2022-09-02 03:39
Were you able to install blobfuse2 with above repo?

**Comment by PkuRainBow** [comment] 2022-09-02 11:01
I find the above [packages-microsoft-prod.deb](https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb) file can only install blobfuse 1.3.8 instead of blobfuse 2.

**Comment by vibhansa-msft** [comment] 2022-09-02 11:42
you need to install blobfuse2 and not blobfuse, can you check the command. We will also validate from our end whether its there in the package or not.

**Comment by vibhansa-msft** [comment] 2022-09-10 03:16
Kindly update you were able to try out blobfuse2 or not. Unless there is an update, will close this item on monday.

**Closed** 2022-09-12 08:41 UTC
Labels: V1

**Comment by martinjoshua** [comment] 2022-11-17 19:00
Hello @vibhansa-msft, we are also experiencing this problem. We have a VM with Ubuntu 22 / blobfuse2 that is uploading data to our storage account. Like the OP above, HNS id disabled. Blobfuse2 is uploading the 0-byte file.

The problem is that our Azure Batch machines are using the Batch Centos image, which when using the SDK  (https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.batch.models.azureblobfilesystemconfiguration?view=azure-dotnet) will mount with blobfuse v1, offering no ability to override. Thus, our Batch machines list 0-byte files instead of directories in the mounted share. Are there any v2 configuration options that can prevent the0-byte file from being created? Or is there any other way to let v1 and v2 of blobfuse to play nicely in the same container?

Thanks!
Joshua

**Comment by vibhansa-msft** [comment] 2022-11-18 02:27
Azure Storage non-HNS accounts do not have any concept of directory. Blobfuse 1/2 being a file-system driver has to deal with directory. In case user executes a 'mkdir' expectation is to create a directory but there is not equivalent thing on storage backend. To solve this problem, we introduced 0 byte stub file to represent a directory. This is by design and cannot be avoided. Only option for now is to migrate to HNS account.
