### ISSUE TITLE
Unable to mount adls gen2 blob containers from a storage account via MSI with private endpoints

### ISSUE THREAD

**Issue by vergilcw** [Azure/azure-storage-fuse#1592] opened 2024-12-16 21:05 UTC
* The blobfuse2 package is not able to mount the blob containers from a storage account using msi on the aml compute instance, except with storage account key authentication which is not feasible from a security perspective. Any Entra-based authentication methods and identities fail to mount with Error 400. (tested versions `2.2.1`, `2.3.0`, and `2.4.0`)
* Our current theory is that something with dns or routing is preventing the authentication traffic from reaching Azure's Entra servers (since the token-based authentication works but not any other method).
* Enabled sdk and debug logging
* Tested mounting from both public compute instance (vweatherfordadmin1)  and private network compute instance (hailmarynumero2) with alternately UMI and System credentials plus SSO enabled. Our testing focused mainly on the private compute instance because we expect the public compute instance to fail given the storage is private 
* tried (temporarily) allowing the public IP of the public compute to access the storage account
* We thoroughly permutated the "msi" authentication mode parameters from this link: https://github.com/Azure/azure-storage-fuse/blob/main/setup/baseConfig.yaml with the following parameters (tested one at a time, and also tested with none of these):
    * `appid`
    * `resid`
    * `objid`
    * `msi_client_id`
* used the UMI, MSI, and even tried SPN identity types, confirmed contributor access to the storage account and container
*	Tested with the `azcli` auth type, but `az login -i` failed to login with the MSI credentials from the compute instance. When attemping az login with auth code as a user, blobfuse was unable to find the user token to attempt the login.
*	tried temporarily allowing DNS queries to bypass internal dns. 
*	Most of the errors given were `400 Identity not found` with `Identity is not assigned to this resource` except when we tried `azcli`, in which case the error was something like `please run az login to setup account` even though we had logged in already with `az login`.

CLI commands / steps to reproduce from the terminal in Azure ML Services:

To reproduce, you need an Azure ML workspace with a compute instance (we used a private network compute instance) and a storage account with an ADLS Gen2 container on a private endpoint. Confirm you can access the storage account from the compute instance using the storage account key. Then, try to mount the storage account using blobfuse2 with MSI authentication. Code snippets are below:

From terminal in Azure ML Services compute instance:
```
#test connectivity
dnslookup <storage-account-name>.dfs.core.windows.net
#(successfully resolving)

#install blobfuse deps:
sudo wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
sudo apt-get install libfuse3-dev fuse3
mkdir ~/test

#testing the mount

sudo blobfuse2 mount ~/test/ --config-file=./config.yaml
cat /var/log/blobfuse2.log | tail -n 15

```

contents of `config.yaml`:
```
allow-other: true

logging:
  type: syslog
  #level: log_err 
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /home/alg/.blobfuse2cache/alg/
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:
  sdk-trace: true
  type: adls
  account-name: <account-name-removed>
  container: storage-bronze
  mode: msi
  appid: <appid-redacted>
  endpoint: https://<account-name-removed>.dfs.core.windows.net
```

**Comment by vibhansa-msft** [comment] 2024-12-17 04:44
```
Tested with the azcli auth type, but az login -i failed to login with the MSI credentials from the compute instance. 
```
This means your compute is not able to access Azure AAD. This is not a Blobfuse issue, there is something wrong with the setup and hence login is not working. 
On your compute can you validate what is the value of "MSI_ENDPOINT" env variable. In ML workspaces generally this is auto created and if it's not set correctly the login shall fail.

**Comment by vergilcw** [comment] 2024-12-17 10:48
```
$ env | grep MSI_ENDPOINT
MSI_ENDPOINT=http://127.0.0.1:46808/MSI/auth
```

The error message:
```
$ az login -i
MSI: Failed to retrieve a token from 'http://127.0.0.1:46808/MSI/auth/?resource=https://management.core.windows.net/&api-version=2017-09-01' with an error of '{"error":"SSO failure, to mitigated it please try to click Jupyter/JupyterLab."}'.
```

Also, the debugging page for MSI auth says to check your MSI endpoint with the following, but here is what I get when running from the AML compute:
```
$ curl 'http://169.254.169.254/metadata/identity/oauth2/token?resource=https://management.core.windows.net&api-version=2018-02-01' -H "Metadata: true"
{"error":"invalid_request","error_description":"Identity not found"}
```

**Comment by vibhansa-msft** [comment] 2024-12-17 11:24
"http://169.254.169.254/metadata/identity/oauth2/token" : this will not work in case of ML environment. If you manually try with "127.0.0.1:46808/MSI/auth" shall work.

**Comment by vibhansa-msft** [comment] 2024-12-18 02:26
Blobfuse will do login to whatever is exposed in MSI_ENDPOINT. If the env variable is not exposed or not being read correctly by blobfuse then it will try on the default endpoint. However, even the azcli is failing for you so may be lets clear that path first.
'azcli' auth means you have logged in already using azcli and blobfuse shall use the token retrieved by it. If you want blobfuse to login and get the token then "msi" shall be used as auth mode.

**Comment by vergilcw** [comment] 2024-12-18 09:58
Thanks for the response! I have been doing more testing but still no luck. 

`az login -i --user <client-id>` works fine to login (but those credentials are not picked up by `blobfuse2`: using the `azcli` type in config.yaml after successfully logging in with `az login`, the `blobfuse2 mount` still errors and says "try running `az login` first"). I confirmed MSI_ENDPOINT is properly set in the `/etc/environment.sso` file and shows up as an environment variable (value is `http://127.0.0.1:46808/MSI/auth`). `az login` seems to pick up that MSI Endpoint though it does not read the MSI client id from that file or because I had to explicitly pass it with the `--user` parameter.  Blobfuse does not seem to pick up either the client ID or the MSI Endpoint.

I tried something else too: In blobfuse2 config.yaml file, there is an advanced parameter called `aadendpoint`. When setting that to `http://127.0.0.1:46808/MSI/auth`, there is an error to the effect that http auth endpoints are not allowed. 

Any ideas on how to get blobfuse2 to read the MSI_Environment variables, or to use the `az login` credentials after successful login?

**Comment by ashruti-msft** [comment] 2024-12-18 21:47
Hi @vergilcw, I have tried your scenario by creating an aml workspace and could not reproduce the issue, I have used public accounts and workspace. Can you confirm me if blobfuse is still detecting "http://169.254.169.254/metadata/identity/oauth2/token" even after successful azcli login?

**Comment by vergilcw** [comment] 2024-12-19 09:51
Hi,

Thanks for the response. I want to confirm we're working from the same set of assumptions for the reproducible example. Here is a description of the setup:

1. A public AML workspace
2. A compute instance (CI) in that AML workspace configured on a private endpoint network, with SSO enabled and an existing User Managed Identity configured in the CI compute settings page.
3. That same User Managed Identity has contributor rights to a separate storage account. The storage account also has a private endpoint.
4. The config.yaml and commands I have tried are described above.

To answer your question, I can confirm that blobfuse is still trying to reach "http://169.254.169.254/metadata/identity/oauth2/token" even after successful azcli login. It's as though the `az login` never happened, i.e. blobfuse is not picking up the stored azcli credentials.

**Comment by souravgupta-msft** [comment] 2024-12-19 11:36
> sudo blobfuse2 mount ~/test/ --config-file=./config.yaml

Hi @vergilcw. Can you please mount blobfuse2 without sudo command and confirm if it is working or not?
You can first login using azcli using the command `az login --identity --username <client_id|object_id|resource_id>`, and then set the login mode to `azcli` in config file.

**Comment by vergilcw** [comment] 2024-12-19 20:40
Yes, that worked! Also now msi auth works as well. The problem was with sudo, I didn't realize it would only work without that. I am in such a habit of using sudo for file system mount commands, I assumed that would be needed here. 

You can close the issue now.

**Comment by vibhansa-msft** [comment] 2024-12-20 03:38
it's not blobfuse issue that it works with or without sudo but rather env issue where your login using azcli is available only in scope of current user and similarly I suspect MSI_ENDPOINT is also not getting exposed to sudo user in your case. May be exporting the MSI_EDNPOINT in .bashprofile might do the trick or you can find other ways (only if you want to mount using sudo, which is in general not required if you are going to use the mount path for yourself). Closing this item here, feel free to post your questions here.

**Closed by vibhansa-msft** 2024-12-20 03:38 UTC
Labels: triaged, V2

**Comment by jainakanksha-msft** [comment] 2024-12-20 05:45
[celebrate]     Akanksha Jain reacted to your message:
________________________________

**Comment by vergilcw** [comment] 2025-01-06 16:17
@jainakanksha-msft, @vibhansa-msft, one thing I didn't notice until just now that means my issue is _not_ solved:

When I run the mount command as the default user called `azureuser` in AML Serviceswithout `sudo` as you suggested, the mount command now works fine and I can list the files within the mount. However, when I try to read a file (e.g. with a simple `cat myfile.txt` from the mounted as the default `azureuser` within azure ML Services, I get a `Permission denied` error. However, I can see from `ls -al` that the permission bits in the file correctly show that `azureuser` should have permission to the file:
`-rw-r----- 1 azureuser azureuser`

This issue suggests that to fix this, mounting with sudo is needed, or possibly adding the user to the `fuse` group:
https://github.com/Azure/azure-storage-fuse/issues/21
(note this is from 2018, is this advice even still relevant?)

Going from the advice given in that issue, I ran:
`sudo addgroup fuse`
to create the fuse group (as it didn't exist before) and then:
`sudo addgroup azureuser fuse` 

But that didn't seem to change the permission error after re-mounting.

Additionally, one comment in the above issue stated that if you are using `allow-other-user=true` setting, you must also have the `user_allow_other` command set in  `/etc/fuse.conf`.  I tried adding that line to the file as well and remounted, but still the same permission error.

Can you please let me know if I am missing something?

Thank you.
