### ISSUE TITLE
Blobfuse2 2.1.0 is using 100% of cpu

### ISSUE THREAD

**Issue by eduardokieling** [Azure/azure-storage-fuse#1256] opened 2023-10-04 10:09 UTC
### Which version of blobfuse was used?
2.1.0

### Which OS distribution and version are you using?
OracleLinux 8.6

### If relevant, please share your mount command.

blobfuse2 mount /backup --config-file=/etc/blobfuse2/streamingConfig.yaml

----------------------------------------------------------------------------
Refer ./setup/baseConfig.yaml for full set of config parameters

allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /backup-cache/blobfuseCache
  timeout-sec: 18000
  max-size-mb: 153600

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name:  XXXXXXXXXXXXXXXXXXXXXXXXXXX
  account-key:  XXXXXXXXXXXXXXXXXXXXXXXXXXX
  endpoint: XXXXXXXXXXXXXXXXXXXXXXXXXXX
  mode: key
  container: backups
  
----------------------------------------------------------------------------

### What was the issue encountered?

Blobfuse2 2.1.0 is using 100% of cpu

### Have you found a mitigation/solution?

No

### Please share logs if available.

During the process of copying to the blob, using the TOP command I can see that 100% of the CPU is being used.

**Comment by vibhansa-msft** [comment] 2023-10-04 10:33
Is it using high cpu only when copies are being done or idle system is also taking high cpu ?

**Comment by eduardokieling** [comment] 2023-10-04 11:04
high cpu only when copies are being done

**Comment by eduardokieling** [comment] 2023-10-04 11:04
> Is it using high cpu only when copies are being done or idle system is also taking high cpu ?

high cpu only when copies are being done

**Comment by edukielingMCD-LEGO** [comment] 2023-11-14 15:29
2.1.1 same behavor, waiting for 2.1.2

**Comment by vibhansa-msft** [comment] 2023-11-15 02:47
We have been trying to reproduce this locally but not observing the same. Can you share exact test case and the file-size that you are using here.

**Comment by vibhansa-msft** [comment] 2023-11-15 09:23
We have some critical bug fixes which need a new release so we will push this item to 2.1.3 as we need to release 2.1.2 soon. Rest assured we are actively working on this item.

**Comment by dkandand** [comment] 2023-11-15 13:11
Performed a database backup. 
Names, versions, result, etc. are in the uploaded Word document: "Blobfuse2 - High CPU Usage.docx"
[Blobfuse2 - High CPU Usage.docx](https://github.com/Azure/azure-storage-fuse/files/13365049/Blobfuse2.-.High.CPU.Usage.docx)

**Comment by vibhansa-msft** [comment] 2023-11-16 04:56
Hi @dkandand thanks for sharing the document. I see as per document overall blobfuse2 process is consuming very high cpu but at the same time, in overall cpu summary in top command I do not see a very high user-space cpu consumption. This might mean CPU is high in kernel space (may be due to reading from disk or network calls). We do not have a oracle DB setup where we can try out the rman backup so from our end we are just trying to upload/download a large file. In this particular test case we do not see much of an issue. Can you share some details on what is the avg file size during this backup and roughly how many files are being synced. Also, share complete config and debug level logs while you observe the high cpu.

**Comment by vibhansa-msft** [comment] 2024-01-02 05:13
Most of our analysis point that CPU is mostly taken up by the network calls. In all pprof analysis it always shows highest contributor as external code and it's called from http client provided by golang. Based on these inputs there is nothing much we can optimize in blobfuse side as such. If you are concerned about the high cpu then you can reduce the parallelism in AzStorage component but that also means you have will lower throughput on network and upload/download jobs will take more time. Closing this as from blobfuse end we do not see any scope of improvement. We are thinking of migrating the latest track-2 go-SDK and we might get some benefits through that in this regard.

**Closed by vibhansa-msft** 2024-01-02 05:13 UTC
Labels: V2
