### ISSUE TITLE
Prevent blobfuse to create empty, dummy files to mark a directory

### ISSUE THREAD

**Issue by tolid** [Azure/azure-storage-fuse#320] opened 2019-10-05 14:09 UTC
### Which version of the blobfuse was used?
1.1.1

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?
Blobfuse creates empty, dummy files to mark a directory with metadata hdi_isfolder=true.
As a result of this it is impossible to download a directory with subdirectories using Azure Storage Explorer on a Windows PC - it will complain "EEXIST: file already exists".

Therefore, I am looking how to prevent blobfuse to create these files or how to clean up them automatically after the creation.

### Have you found a mitigation/solution?
No

### If relevant, please share your mount command.
/usr/bin/blobfuse /blob/ --tmp-path=/mnt/resource/blobfusetmp --config-file=/root/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other --log-level=LOG_DEBUG

**Comment by amnguye** [comment] 2019-10-07 15:34
Hi Tolid,

This is actually expected behavior by blobfuse and implemented by design. I'm sorry there isn't currently a way we can prevent blobfuse from doing this and to remove those files after creation.

This is actually a duplicate of this github issue (#280).

Is it possible if you could tell me what you're trying to achieve? Is it just uploading a directory and downloading it?

**Comment by tolid** [comment] 2019-10-08 20:12
Hi amnguye,

We use blobfuse mount on a Linux PC for uploading data. The data structure contains data files in many sub directories. Later the data should be downloaded  on a Windows using Azure storage explorer - by clicking on top-level folder and selecting option "download folder" . However download will fail because Windows does not accept a file (empty blob with metadata hdi_isfolder=true) and a sub-directory with the same name: you can't have file with name A and sub-directory with name A in a directory on NTFS.

**Comment by amnguye** [comment] 2019-10-08 21:33
Hi Tolid,

With what you're trying to do, I don't think blobfuse would be a viable solution for you. Since what you're trying to achieve on the Linux side is "uploading data" that contains "data files in many subdirectories" can I suggest another supported application?

https://github.com/Azure/azure-storage-azcopy
AzCopy would be a good application to use and a supported scenario since you are trying to upload and download directories with subdirectories and its extremely efficient in doing so.

**Closed** 2020-06-16 17:41 UTC
