### ISSUE TITLE
blobfuse requires an os.makedirs() for writing blobs to a path in a container

### ISSUE THREAD

**Issue by rfernand2** [Azure/azure-storage-fuse#363] opened 2020-02-13 02:41 UTC
### Which version of the blobfuse was used?
Unknown 

### Which OS (please include version) are you using?
Linux 

### What problem was encountered?
I have mounted an Azure storage container as read/write.  From my python ML app, I can create a blob on the top level of the container, as expected (using python `open()`, `write()` api's).  If I need to write a blob with a path in it's name, I get the error "file or directory not found".  

If I call `os.makedirs()` first on the path part of the name, I can then create the blob, but this results in the infamous **blobfuse directory marker** problem (where I cannot download the resulting directory tree due to 0-length files conflicting with the directory names on my local file system).  

Can you change this behavior to either:
   1. support the creation of pathed-blobs without requiring directory creations (like Azure blobs normally work)
   or
   2. support the creation of directories without the ill-effects of creating the directory markers (like a file systems normally work)

### Have you found a mitigation/solution?
No.  

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No.

**Comment by amnguye** [comment] 2020-02-18 16:46
Hi,

Sorry for the late response. This is a duplicate of #280 and #320 

We will not change the behavior of how directories are made. This would be a breaking change. If no directory marker is there, blobfuse (and other applications) would not be able to identify if a directory existed.

**Closed** 2020-06-23 17:20 UTC
Labels: duplicate
