### ISSUE TITLE
Unable to start blobfuse due to a lack of credentials

### ISSUE THREAD

**Issue by rudolfdobias** [Azure/azure-storage-fuse#958] opened 2022-11-02 17:10 UTC
### Which version of blobfuse was used?
1.3.8

### Which OS distribution and version are you using?
Ubuntu 20.04 running in Docker

### If relevant, please share your mount command.

```
export AZURE_STORAGE_AUTH_TYPE=Key
export AZURE_STORAGE_ACCOUNT=xxx
export AZURE_STORAGE_ACCESS_KEY=yyy
export AZURE_STORAGE_BLOB_ENDPOINT=https://xxx.blob.core.windows.net

mkdir -p /mnt/test
blobfuse /mnt/test --tmp-path=/tmp/blobfuse --container-name=builders
```

### What was the issue encountered?
Error: **Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.**
 - Tried using config file, no effect
 - Tried using another auth method, no effect
 - Tried using --log-level=LOG_DEBUG, no effect (no new logs)

### Have you found a mitigation/solution?
No.

### Please share logs if available.
No more logs ...

**Comment by rudolfdobias** [comment] 2022-11-02 17:15
Same behavior after upgrading to 1.4.5 ...

**Comment by vibhansa-msft** [comment] 2022-11-03 07:35
These export of environment variables you are doing in host machine/vm or inside the docker. If they are exported in host OS then docker will not have access to those. Also, to run blobfuse in docker image you need to enable /dev/fuse device inside and have kernel capabilities of SYS_ADMIN.

 Below is a sample command to launch a container where you can use blobfuse:
`docker run -it --rm --cap-add=SYS_ADMIN --device=/dev/fuse --security-opt apparmor:unconfined -e AZURE_STORAGE_ACCOUNT -e AZURE_STORAGE_ACCESS_KEY -e AZURE_STORAGE_ACCOUNT_CONTAINER <docker image>`

We are currently working on next generation of blobfuse aka blobfuse2. It's in preview mode as of now and will be GAed soon. As of now we do have a docker image published without preview version which can be used for similar test cases. You can refer to wiki around this [here](https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Docker-Container)

**Comment by rudolfdobias** [comment] 2022-11-03 10:16
Thanks for reply. These envs were declared inside a running container, from the same context as the blobfuse command is run. The problem then would be the SYS_ADMIN capability because the container runs in AKS. Maybe it would be good to put in the docs that there are these constraints?

In this case I'm not going to use blobfuse in the AKS, I'll manage another way. Still I sense the error message "Unable to start blobfuse due to a lack of credentials" is quite misleading in this particular case, because the config values have been met.

**Comment by vibhansa-msft** [comment] 2022-11-03 10:31
These things are mentioned in the wiki that I have just shared. 
Also, for AKS we have a specialized offering called 'Blob CSI Driver' and that allows you to use blobfuse implicitly.
https://github.com/kubernetes-sigs/blob-csi-driver

**Comment by vibhansa-msft** [comment] 2022-11-03 16:37
One more point, running container with any fuse based system requires SYS_ADMIN and /dev/fuse parameters. This is not a limitation from Blobfuse end. You can give blobfuse2 a try and that shall provide correct error message. Closing this as this is not a bug from blobfuse side.

**Closed by vibhansa-msft** 2022-11-03 16:37 UTC
Labels: V1
