### ISSUE TITLE
examples of how to connect to adls gen 2 filesystem and folders using config file

### ISSUE THREAD

**Issue by kk921dbg** [Azure/azure-storage-fuse#537] opened 2020-12-04 18:11 UTC
### If relevant, please share your mount command.
Thats what we are looking for

**Comment by vibhansa-msft** [comment] 2020-12-05 07:32
Mount command
-------------------
blobfuse <Mount dir> --tmp-path=<Cache dir> --config-file=<Config file> --use-attr-cache=true --use-adls=true --file-cache-timeout-in-seconds=120 -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120

<Config file>
----------------
- For Account key
	accountName <storage account>
	accountKey <storage account key>
	authType Key
	accountType adls
	containerName <name of the container to be mounted>

- For SPN
	accountName <storage account>
	authType SPN
	servicePrincipalClientId <Client id>
	servicePrincipalTenantId <Tenant id>
	servicePrincipalClientSecret <Client secret>
	accountType adls
	containerName <storage container to be mounted>


Note:
-------
- For both <Mount dir> and <Cache dir> user shall have rwx permissions
- "--log-level=LOG_DEBUG" to enable debug logs which goes to syslog
- Refer to Readme for more config and command line options
- Some of the config parameters can be given through environment variables, refer Readme for the same
- use-adls is to mark that the storage account is ADLS account, by default blobfuse considers it to be a BlockBlob account

**Comment by vibhansa-msft** [comment] 2020-12-07 02:30
Hope the above information helps. In case of any further queries, you can post on this thread.

**Comment by Madhuriv23** [comment] 2020-12-07 10:53
We tried running with the above-specified config and seeing the below error (blobfuse v1.3.6-Redhat)

	export AZURE_STORAGE_ACCOUNT=
	export AZURE_STORAGE_AUTH_TYPE=SPN
	export AZURE_STORAGE_SPN_CLIENT_ID=
	export AZURE_STORAGE_SPN_TENANT_ID=
	export AZURE_STORAGE_SPN_CLIENT_SECRET=
	blobfuse /home/bdaa-admin/container --container-name=vmgen2container --tmp-path=/home/bdaa-admin/temp  --use-adls=true


Dec  7 11:47:02 vm-dev-bdaa-support blobfuse[6042]: Initializing blobfuse using DataLake
Dec  7 11:47:02 vm-dev-bdaa-support blobfuse[6042]: ** Delaying authentication to post fork for older curl versions
Dec  7 11:47:02 vm-dev-bdaa-support blobfuse[6043]: ** Post fork authentication for older libcurl version
Dec  7 11:47:02 vm-dev-bdaa-support blobfuse[6043]: refresh callback set
Dec  7 11:47:02 vm-dev-bdaa-support blobfuse[6043]: calling refresh token
Dec  7 11:47:07 vm-dev-bdaa-support blobfuse[6043]: ==> REQUEST/RESPONSE :: POST https://login.microsoftonline.com/e00ddcdf-1e0f-4be5-a37a-894a4731986a/oauth2/v2.0/token?&Content-Type=application/x-www-form-urlencoded&Content-Length=160&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 0 ::
Dec  7 11:47:07 vm-dev-bdaa-support blobfuse[6043]: OAUTH Token : Refresh token failed Failed to retrieve OAuth Token (CURLCode: 56, HTTP code: 0):
Dec  7 11:47:07 vm-dev-bdaa-support blobfuse[6043]: Unable to retrieve OAuth token: Failed to retrieve OAuth Token (CURLCode: 56, HTTP code: 0):
Dec  7 11:47:07 vm-dev-bdaa-support blobfuse[6043]: Failed to get token using SPN credentials.
Dec  7 11:47:07 vm-dev-bdaa-support blobfuse[6043]: Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.
Dec  7 11:48:01 vm-dev-bdaa-support systemd: Started Session 32 of user root.
Dec  7 11:49:01 vm-dev-bdaa-support systemd: Started Session 33 of user root.

**Comment by NaraVen** [comment] 2020-12-07 18:38
This is a connectivity issue caused due to Curl versions. Which RPM did you consume? The RPM for 7.5 or the RPM for 7.8. I see that you are using RHEL 7.7 and we have not tested with RHEL 7.7. Is it possible to upgrade to RHEL 7.8?

**Comment by Madhuriv23** [comment] 2020-12-08 13:10
@NaraVen, I tried on RHEL 7.8 and still get the same error

Dec  8 14:06:32 vm-blobfuse blobfuse[3053]: ** Delaying authentication to post fork for older curl versions
Dec  8 14:06:32 vm-blobfuse kernel: fuse init (API version 7.23)
Dec  8 14:06:32 vm-blobfuse systemd: Mounting FUSE Control File System...
Dec  8 14:06:32 vm-blobfuse systemd: Mounted FUSE Control File System.
Dec  8 14:06:32 vm-blobfuse blobfuse[3062]: ** Post fork authentication for older libcurl version
Dec  8 14:06:37 vm-blobfuse blobfuse[3062]: ==> REQUEST/RESPONSE :: POST https://login.microsoftonline.com/e00ddcdf-1e0f-4be5-a37a-894a4731986a/oauth2/v2.0/token?&Content-Type=application/x-www-form-urlencoded&Content-Length=160&Transfer-Encoding=--------------------------------------------------------------------------------RESPONSE Status :: 0 ::
Dec  8 14:06:37 vm-blobfuse blobfuse[3062]: OAUTH Token : Refresh token failed Failed to retrieve OAuth Token (CURLCode: 56, HTTP code: 0):
Dec  8 14:06:37 vm-blobfuse blobfuse[3062]: Unable to retrieve OAuth token: Failed to retrieve OAuth Token (CURLCode: 56, HTTP code: 0):
Dec  8 14:06:37 vm-blobfuse blobfuse[3062]: Failed to get token using SPN credentials.
Dec  8 14:06:37 vm-blobfuse blobfuse[3062]: Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.

**Comment by NaraVen** [comment] 2020-12-08 18:17
@Madhuriv23 , are you using RHEL 7.8 rpm?

**Comment by Madhuriv23** [comment] 2020-12-09 07:49
yes. blobfuse-1.3.6-RHEL-7.8-x86_64.rpm

**Comment by NaraVen** [comment] 2020-12-09 09:47
Could you try this from the Shell prompt and see if it errors out or returns a token?

curl -X GET -H 'Content-Type: application/x-www-form-urlencoded' \
-d 'grant_type=client_credentials&client_id=<your_spn_client-id>&resource=<https://<your_storage_ACCOUNT_NAME>.blob.core.windows.net>&client_secret=<your_spn_secret>' \
https://login.microsoftonline.com/<spn-tenant-id>/oauth2/token

**Comment by Madhuriv23** [comment] 2020-12-09 13:11
@NaraVen

Please find below the output of the curl with debug enabled

curl -X GET -H 'Content-Type: application/x-www-form-urlencoded' -d 'grant_type=client_credentials&client_id=d416da6b-88f9-41e6-85de-27cb9e743da1&resource=https://vmgen2test.blob.core.windows.net&client_secret=TpPB6Hzjqg170IF-52sN' https://login.microsoftonline.com/oauth2/token -v
* About to connect() to proxy 10.123.0.132 port 3128 (#0)
*   Trying 10.123.0.132...
* Connected to 10.123.0.132 (10.123.0.132) port 3128 (#0)
* Establish HTTP proxy tunnel to login.microsoftonline.com:443
> CONNECT login.microsoftonline.com:443 HTTP/1.1
> Host: login.microsoftonline.com:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
> Content-Type: application/x-www-form-urlencoded
>
< HTTP/1.1 200 Connection established
<
* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=stamp2.login.microsoftonline.com,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
*       start date: Oct 13 00:00:00 2020 GMT
*       expire date: Oct 12 23:59:59 2021 GMT
*       common name: stamp2.login.microsoftonline.com
*       issuer: C=DE,ST=Hesse,L=Eschborn,O=Deutsche Boerse AG,OU=Connectivity Control & Internet,CN=cipfh101.deutsche-boerse.de,E=cci@deutsche-boerse.com
> GET /oauth2/token HTTP/1.1
> User-Agent: curl/7.29.0
> Host: login.microsoftonline.com
> Accept: */*
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 161
>
* upload completely sent off: 161 out of 161 bytes
< HTTP/1.1 404 Not Found
< Cache-Control: private
< Content-Length: 0
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-Content-Type-Options: nosniff
< P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
< x-ms-request-id: 6681e451-8766-4889-bfc2-13ae46da2700
< x-ms-ests-server: 2.1.11303.13 - NEULR2 ProdSlices
< Date: Wed, 09 Dec 2020 13:10:13 GMT
< Proxy-Connection: Keep-Alive
< Connection: Keep-Alive
< Set-Cookie: x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly
<
* Connection #0 to host 10.123.0.132 left intact

**Comment by NaraVen** [comment] 2020-12-10 04:56
Hi @Madhuriv23 , I reproduced this issue, there is a bug and the root cause is #540 . I am closing this issue and lets follow up in #540 .
The workaround I recommend is using Storage Key (authType key). Container level Sas Token will also work with ADLS Gen 2. (authType sas) We will fix this in Dev soon and push it in our next release.

**Closed** 2020-12-10 04:56 UTC
Labels: question
