### ISSUE TITLE
Why not use DFS endpoint when upload a file with ADLS type (compare with goofys)?

### ISSUE THREAD

**Issue by Lyndon1994** [Azure/azure-storage-fuse#1090] opened 2023-03-21 05:09 UTC
### Which version of blobfuse was used?
v2

### Which OS distribution and version are you using?
ubuntu18.04

### If relevant, please share your mount command.
```
go build -tags=fuse2
./azure-storage-fuse mount --config-file=./sampleFileCacheConfig.yaml /home/azureuser/mnt/blobfusev2
```
sampleFileCacheConfig.yaml:
```
# Refer ./setup/baseConfig.yaml for full set of config parameters

allow-other: true

logging:
  type: syslog
  level: log_warning

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /home/azureuser/mnt/tmp_file_v2
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:
  type: adls
  account-name: xxx
  account-key: xxx
  endpoint: https://xxx.dfs.core.windows.net
  mode: key
  container: test
```

### What was the issue encountered?

I compared the write file performance of **blobfusev2** and **goofys** and found that blobfusev2 is much slower. 
I found that they were all written concurrently, but the requested URLs were different. Blobfuse uses the **blob** API, and goofys uses the **adls** API. I don't know if this has anything to do with it. Why doesn't blobfuse use the adls api? For what consideration?

![image](https://user-images.githubusercontent.com/13145082/226522645-5fc7df25-350c-46da-9c93-1e79e1af7aaf.png)

blobfuse's url: https://xxx.blob.core.windows.net/test/Benchmark/blobfusev2/0000.txt
goofys's url: https://xxx.dfs.core.windows.net/test/Benchmark/goofys/0000.txt?action=append&position=948961280
doc: https://learn.microsoft.com/vi-vn/rest/api/storageservices/datalakestoragegen2/path/update#request-body

**Comment by vibhansa-msft** [comment] 2023-03-21 05:21
Using Blob endpoints for read/write is a design choice we have made to be cross tool compatible. A file created using DFS endpoint cannot be written using blob endpoint. There are lot of other tools we also do read/write operation using blob endpoint and hence this choice.

For goofy vs Blobfuse2 I see a difference in the approach. blobfuse2 first caches entire content on disk and then on close uploads entire file in parallel. Goofys might be appending to existing file in blocks as you write. However, there is a good amount of feature difference in what blobfuse2 offers compared to Goofys.

Also, for the performance part : Blobfuse2 will give optimal performance on fuse3 compliant systems. Can you run your comparison tests on Ubn-20/22.

**Comment by Lyndon1994** [comment] 2023-03-21 05:34
Thank you for responding so quickly. I'll give it a try.

**Comment by Lyndon1994** [comment] 2023-03-21 11:31
This is benchmark in Ubuntu 20.04.
same cmd but use fuse3 and same storage and same test script.

![image](https://user-images.githubusercontent.com/13145082/226593621-47f87905-9653-40ec-8a9a-0cb9049d5ee0.png)

**Comment by Lyndon1994** [comment] 2023-03-23 05:08
yes, It's the same when I use blob endpoint.

The blobfuse mount command is in the description above.

test script:
rwtest.py: 
[rwtest.txt](https://github.com/Azure/azure-storage-fuse/files/11047161/rwtest.txt)

```
fuse=$1
python2 rwtest.py -rootPath /home/azureuser/mnt/$fuse/Benchmark/$fuse -fileSize 1000000000 -fileCount 1 -sync True -testMethod test_write -bufferSize 16777216 -skipCheck True -cleanFiles True
```

**Comment by vibhansa-msft** [comment] 2023-03-27 05:05
Perf optimization is an ongoing item in blobfuse2.
For the other suggestion on using DFS endpoint to upload/download file, by design we have chosen this path and we will not be using the other end point to support cross tool compatibility. Closing this as there is no real action item here other than perf optimization. Feel free to post here if you have any questions, or re-open this if you feel there is some bug in blobfuse code.

**Closed** 2023-03-27 05:07 UTC
Labels: performance
