### ISSUE TITLE
Blob container "subdirectory" accessible by Azure Portal but not when mounted via blobfuse

### ISSUE THREAD

**Issue by mawah** [Azure/azure-storage-fuse#48] opened 2018-01-12 17:13 UTC
Hi folks,

A client has uploaded data to a blob storage container in a series of "subdirectories" (for lack of a better term since this is blob storage) named by year.  There appears to have been a glitch that affects just one of these subdirectories, and only when it is accessed via blobfuse. We can visualize the contents of the subdirectory in Azure Portal (screenshot: https://imgur.com/yLV2gvm), but not when the container has been mounted via blobfuse (screenshot: https://imgur.com/fagLJyb). Mounting via blobfuse was performed as a startup task in Batch AI.

Please feel free to reach out to me at alias mawah. Thanks a bunch!

**Comment by AlexanderYukhanov** [comment] 2018-01-12 17:16
I have got access to this vm
Here is the ls output:
$ ls -l /mnt/batch/tasks/shared/LS_root/mounts/blobfuse/data/v1
ls: cannot access '/mnt/batch/tasks/shared/LS_root/mounts/blobfuse/data/v1/2012': No such file or directory
total 16
drwxrwx--- 3 root root 4096 Jan  1  1970 2010
drwxrwx--- 3 root root 4096 Jan  1  1970 2011
d????????? ? ?    ?       ?            ? 2012
drwxrwx--- 3 root root 4096 Jan 12 16:26 2013
drwxrwx--- 3 root root 4096 Jan 12 16:22 2014
drwxrwx--- 3 root root 4096 Jan 12 16:20 2015
drwxrwx--- 3 root root 4096 Jan 12 16:17 2016

Here is the state of the cache:
$ sudo ls -la /mnt/batch/tasks/startup/wd/cache/blobfuse/root/data/v1
total 24
drwxrwx--- 6 root root 4096 Jan 12 16:26 .
drwxrwx--- 3 root root 4096 Jan 12 16:17 ..
drwxrwx--- 3 root root 4096 Jan 12 16:26 2013
drwxrwx--- 3 root root 4096 Jan 12 16:22 2014
drwxrwx--- 3 root root 4096 Jan 12 16:20 2015
drwxrwx--- 3 root root 4096 Jan 12 16:17 2016

**Comment by AlexanderYukhanov** [comment] 2018-01-12 17:48
Enabled debug logging and remounted.
$ls -l /mnt/bfs/data/v1/2012
logs:
Making directory /mnt
Making directory /mnt/cache
Making directory /mnt/cache/root
azs_getattr called, Path requested = /data
accessing mntPath = /mnt/cache/root/data returned -1
Directory data/ found with return value: 1!
azs_getattr called, Path requested = /data/v1
accessing mntPath = /mnt/cache/root/data/v1 returned -1
Directory data/v1/ found with return value: 1!
azs_getattr called, Path requested = /data/v1/2012
accessing mntPath = /mnt/cache/root/data/v1/2012 returned -1

**Comment by AlexanderYukhanov** [comment] 2018-01-12 19:44
The issue is in incorrect loop condition at blobfuse/utilities.cpp:284
 } while ((continuation.size() > 0) && !success && (failcount < 20));

In this case the first request for blobs returns an empty blobs list but has continuation token. If we would continue we will get blobs.

**Comment by AlexanderYukhanov** [comment] 2018-01-12 19:45
it should be  while ((continuation.size() > 0) || !success && (failcount < 20));

**Comment by AlexanderYukhanov** [comment] 2018-01-12 19:50
https://github.com/Azure/azure-storage-fuse/pull/49

**Comment by mawah** [comment] 2018-01-12 19:58
Thanks a bunch, Alex! Your suggestion to create an empty ".directory" file and upload it to the "2012" folder using Azure Storage Explorer did the trick for me. I realize you might want to keep the git issue open while pushing a fix, but for me the issue is resolved. Thanks again!

**Comment by AlexanderYukhanov** [comment] 2018-01-12 20:14
Yes, there is a work around - you need to put an empty file into affected folder (e.g. put empty .directory file)

**Comment by seguler** [comment] 2018-01-13 17:55
This is now fixed in the dev branch. We'll release sometime next week. 

Thanks for reporting @mawah and thanks for fixing @AlexanderYukhanov

**Comment by seguler** [comment] 2018-01-16 18:49
This is now released as part of blobfuse 0.2.2. Closing the issue.

**Closed by seguler** 2018-01-16 18:49 UTC
