### ISSUE TITLE
Secret header incorrectly set when talking to MSI_ENDPOINT

### ISSUE THREAD

**Issue by sweana** [Azure/azure-storage-fuse#355] opened 2020-01-21 21:56 UTC
### Which version of the blobfuse was used?
v1.1.1

### Which OS (please include version) are you using?
ubuntu 18.04

### What problem was encountered?
requests sent to MSI_ENDPOINT should have a header named "Secret" whose value should be obtained from the MSI_SECRET environment variable.

**Comment by NaraVen** [comment] 2020-05-03 02:58
I could not reproduce this one. So, I am closing this issue.

**Closed by NaraVen** 2020-05-03 02:58 UTC
