### ISSUE TITLE
Directory names in mount on ubuntu 18.04 docker remove first letter and files add . and some chars at the end.

### ISSUE THREAD

**Issue by augcampos** [Azure/azure-storage-fuse#195] opened 2018-07-03 20:39 UTC
I have a docker, ubuntu 18.04 that mount a azure blog ab-x in /var/azure/ab-x
`blobfuse /var/azure/ab-x --tmp-path=/tmp/blobfuse/ab-x --container-name=ab-x -o allow_other -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120`

then execute :
```
cd /var/azure/ab-x
mkdir pool/master
rsync -au /var/files/*txt pool/master/
```
on the Azure Storage Explorer (preview) i got:

ab-x/
 -- /pool/
 --- /master/
 **--  /ool (1)
 --- /master/
 ----.file1.txt.3Ikqwr   (2)
 ----.file3.txt..cA1yIi   (2)**
      
Directory names in mount on ubuntu 18.04 docker remove first letter(1) and files add . and some chars at the end(2).

**Comment by seguler** [comment] 2018-07-09 20:23
Could this be some kind of artifact of rsync ? Do you still see these files exist even after rsync completes ? Has the rsync process returned any errors ?

**Comment by augcampos** [comment] 2018-07-09 21:59
_<Could this be some kind of artifact of rsync ?_ 
No the rsync already finished and the files that should exist do not.
_<Do you still see these files exist even after rsync completes ?_ 
Yes they are permanent after rsyn  completes
_<Has the rsync process returned any errors ?_
No errors.

**Comment by seguler** [comment] 2018-07-13 06:51
I just tried the exact same thing; and couldn't reproduce the issue :(

root@3f20c2b582a8:/var/azure/ab-x# rsync -au /var/files/*txt pool/master/
root@3f20c2b582a8:/var/azure/ab-x# cd pool
root@3f20c2b582a8:/var/azure/ab-x/pool# cd master
root@3f20c2b582a8:/var/azure/ab-x/pool/master# ls
file1.txt
root@3f20c2b582a8:/var/azure/ab-x/pool/master# ls -alrt
total 12
-rwxrwxrwx 1 root root    6 Jul 13 06:50 file1.txt
drwxrwxrwx 3 root root 4096 Jul 13 06:50 ..
drwxrwxrwx 2 root root 4096 Jul 13 06:50 .

**Comment by seguler** [comment] 2018-07-13 06:57
Here is another test; I used the exact command you used:

```
root@3f20c2b582a8:/var# blobfuse /var/azure/ab-x --tmp-path=/tmp/blobfuse/ab-x --container-name=ab-x -o allow_other                                                                      
root@3f20c2b582a8:/var#
root@3f20c2b582a8:/var#
root@3f20c2b582a8:/var# cd /var/azure
root@3f20c2b582a8:/var/azure# ls
ab-x
root@3f20c2b582a8:/var/azure# cd ab-x
root@3f20c2b582a8:/var/azure/ab-x# mkdir -p pool/master
root@3f20c2b582a8:/var/azure/ab-x# echo "Hello woooooorld" > /var/files/abc.txt
root@3f20c2b582a8:/var/azure/ab-x# rsync -au /var/files/*txt pool/master/
root@3f20c2b582a8:/var/azure/ab-x# cd pool
root@3f20c2b582a8:/var/azure/ab-x/pool# cd master
root@3f20c2b582a8:/var/azure/ab-x/pool/master# ls -lart
total 16
-rwxrwxrwx 1 root root   17 Jul 13 06:54 abc.txt
drwxrwxrwx 3 root root 4096 Jul 13 06:54 ..
-rwxrwxrwx 1 root root    6 Jul 13 06:54 file1.txt
drwxrwxrwx 2 root root 4096 Jul 13 06:54 .
root@3f20c2b582a8:/var/azure/ab-x/pool/master# more abc.txt
Hello woooooorld
root@3f20c2b582a8:/var/azure/ab-x/pool/master#
```

Here is my dockerfile:
```
FROM ubuntu:18.04

# disable interactive functions
RUN apt-get update && \
    apt-get install wget -y && \
    wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get install fuse blobfuse -y && \
    apt-get install libcurl3-gnutls libgnutls30 -y && \
    mkdir -p /var/azure/ab-x && \
    mkdir -p /var/files/ && \
    mkdir -p /var/cache/ && \
    echo "Hello" > /var/files/file1.txt
# Set environment variables.

ENV AZURE_STORAGE_ACCOUNT myaccount
ENV AZURE_STORAGE_SAS_TOKEN ?redacted

# Define working directory.
WORKDIR /root
```

What is the difference between your tests and my tests ?

**Comment by augcampos** [comment] 2018-07-16 10:23
I use this for a private debian repositoy.
I end up use the FILE SERVICE and mount it as type "cifs" and work for me.
Thanks

**Comment by seguler** [comment] 2018-07-16 21:09
Ok closing this since you found an alternative

**Closed by seguler** 2018-07-16 21:09 UTC
Labels: question
