### ISSUE TITLE
Blobfuse 1.1.1 not works on new Azure Ubuntu 18.04 VM after 2020.9.2

### ISSUE THREAD

**Issue by mslichao** [Azure/azure-storage-fuse#463] opened 2020-09-02 23:41 UTC
### Which version of the blobfuse was used?
1.1.1

### Which OS (please include version) are you using?
"imageReference": {
  "publisher": "Canonical",
   "offer": "UbuntuServer",
  "sku": "18.04-LTS",
  "version": "latest"
}

### What problem was encountered?
blobfuse 1.1.1 is the best stable version I used, it works well on Ubuntu before 2020.9.1
After 2020.9.1, Azure release a new image version 18.04.202009010 (Use `az vm image list --location westus2 --publisher Canonical --offer UbuntuServer --sku 18.04-LTS --all --output table` to show all the version), but blobfuse 1.1.1 not work on the image.
Repro steps:
1. Create a new VM with Ubuntu 18.04 after 2020.9.2
2. Install blobfuse 1.1.1
3. Mount a storage container
There is nothing error message when run blobfuse to mount a container, but blobfuse is not list in `ps -aux`

### Have you found a mitigation/solution?
Use Azure Resource Template to create a new VM, and set the image version to `18.04.202008180`

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No, there is nothing log in syslog

**Comment by cris-b** [comment] 2020-09-03 10:44
1.3.1 works, but since 1.1.1 I had issues with transport disconnected, will see if it still happens on 1.3.1..

**Comment by cris-b** [comment] 2020-09-03 10:47
this seems similar to what happens on RHEL 8.2 with all versions now,  but 1.3.1 fixes it on Ubuntu 18.04

**Comment by cris-b** [comment] 2020-09-04 08:37
1.3.1 has issues for me with transport disconnected..

so on ubuntu 18.04 now there is:

1.1.1 - does not mount
1.2.0-1.3.1 - random transport disconnected messages

so blobfuse is now unusable on yet another linux distro...

**Comment by vibhansa-msft** [comment] 2020-09-04 10:28
@cris-b Kindly share syslogs with 1.3.1 (LOG_DEBUG) where you observe transport disconnected error.

**Comment by cris-b** [comment] 2020-09-04 12:16
so the issue is because 1.1.1 sets max_write to 4194304 in line 218 of blobfuse.cpp.  

New ubuntu 18.04 comes with kernel 5.4 which does not like this.  Later versions of blobfuse have a check for kernel 5.4.  Commenting out the line in 1.1.1 will make 1.1.1 work in latest ubuntu 18.04.  So you should still be able to use latest ubuntu with 1.1.1.....

**Comment by vibhansa-msft** [comment] 2020-09-04 12:56
But with this config it will fail in mount itself so Transport disconnection shall be a different error I suppose.

**Comment by cris-b** [comment] 2020-09-04 13:00
yes agreed, I'll attempt to get logs with 1.3.1

**Comment by vibhansa-msft** [comment] 2020-09-09 02:50
Check for kernel version 5.4 has been lowered in latest version 1.3.2. Now it shall work on Ubuntu 18.04. Give it a try and share the logs if you still face disconnection issues.

**Comment by NaraVen** [comment] 2020-09-10 16:34
@mslichao, Could you please take version 1.3.2 instead of 1.1.1? 1.3.2 is the latest.

**Comment by NaraVen** [comment] 2020-09-10 16:37
> 1.3.1 has issues for me with transport disconnected..
> 
> so on ubuntu 18.04 now there is:
> 
> 1.1.1 - does not mount
> 1.2.0-1.3.1 - random transport disconnected messages
> 
> so blobfuse is now unusable on yet another linux distro...

@cris-b We have many customers running blobfuse on Ubuntu 18.04 and they do not get the transport endpoint error. So I would like to help you with your concern. Is your blobfuse process getting OOMKilled ? How much memory do you have . Could you please send the output of ps -aux | grep blobfuse and the output of df -h

**Comment by NaraVen** [comment] 2020-09-13 08:36
I am closing this one since many clients have successfully used blobfuse 1.3.2 in the latest upgrade Ubuntu 18.04 . If you have any issues please reopen.

**Closed by NaraVen** 2020-09-13 08:36 UTC
Labels: triaged

**Comment by cris-b** [comment] 2020-09-14 10:43
> yes agreed, I'll attempt to get logs with 1.3.1

added logs in new bug #470
