### ISSUE TITLE
Blobfuse uploads 0-length files to container, and all files end up in /p/root/... (issue with tmp-path on lvm-ext4)

### ISSUE THREAD

**Issue by anisoptera** [Azure/azure-storage-fuse#222] opened 2018-09-25 19:37 UTC
### Which version of the blobfuse was used?
Latest master, 923985c062a18ec2c0dd7118f6adbe4ff4478d46

### Which OS (please include version) are you using?
Ubuntu 18.04

### What problem was encountered?
I copied files to the mount. In the Azure view of the container, I see the file names created with 0 length. There is also a /p/root directory which appears to contain all the files I uploaded with their proper lengths. I see the /p/root directory on my local system as well.

Currently, the files have their proper sizes in both places on my local system. However, I previously uploaded several hundred GB using this tool, and when I remounted the container some time later, they showed as 0 length, and attempting to read the files resulted in them being treated as 0-length. They were also 0 length in the container.

At the time, I didn't know about the /p directory, so I ended up deleting them all and starting this copy. That's when I discovered this issue.

### Have you found a mitigation/solution?
I can use the /p/root version, I guess, but that doesn't seem like a good solution. What happens if I want to modify a file?

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
There are no errors in the syslog.

### If relevant, please share your mount command.
`./blobfuse /mnt/imagenet --tmp-path=/mnt/blobfusetmp -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --config-file=../connection.cfg` - basically just `mount.sh`.

**Comment by seguler** [comment] 2018-10-01 17:45
Can you check the metadata on the 0 length files ? Right click on the blobs on the Storage Explorer and confirm whether you see a metadata called hdi_isfolder=true ? I suspect you may be confusing directory markers with the files you have uploaded. Blobfuse will create empty, dummy files to mark a directory. It will have 0 file length and metadata hdi_isfolder=true

**Comment by anisoptera** [comment] 2018-10-01 21:14
I can't check anymore as I deleted the container and reuploaded using azcopy. But I'm not sure why it would create a bunch of directory markers for uploaded files? That seems like a bug too.

The 0-length files also showed as regular files on my local machine as well. I do know what the 0-length directory markers look like, I saw those show up when there was an empty directory - but these weren't directories.

When I uploaded the files, I copied them to the mount point. They showed as having their proper sizes. Then, after some time, during which I saw a lot of upload activity across the network, they shifted to being size 0 locally. I actually thought that this just was an artifact of them being removed from the local cache. It wasn't until some time later when I remounted the storage that I discovered that the files were actually in this state.

I don't know if it's still an issue - this all happened over the course of a couple of months - but there hasn't been an update to the master branch in quite some time, so if it has been fixed, it's something that happened on the blob storage service side, rather than blobfuse.

**Comment by talbt** [comment] 2018-10-03 21:52
I've observed similar behaviour, this seems to be connected to the device backing blobfuse buffer cache. Placing tmp-path on lvm-ext4 mount (rw,realtime.seclabel,data=ordred) had similar results, some files have been placed in [container/dst/...]with 0 length, and in my case the missing files were placed in [container/<empty folder>/root/dst/...] with correct length.  Placing the tmp-path back on ram-tmpfs resolved the issue for me. Perhaps good idea would be to have a check in place if the device backing tmp-path is compatible.

**Comment by anisoptera** [comment] 2018-10-04 00:14
Ah, I too was putting the temp path on an lvm-ext4 mount, though I don’t
recall the exact mount flags (just defaults I think, it isn’t in fstab)

Agree, if there are specific requirements of the temp file system, it’d
help to document them and check at runtime.

**Comment by seguler** [comment] 2018-10-04 03:00
Wow - thanks for the details.. Didn't think we'd have an issue when tmp-path is on lvm-ext4. For now labeling this as a bug so that others are warned. Meanwhile I'll test and confirm.

**Comment by talbt** [comment] 2018-10-04 08:47
I've did some extra tests, and lvm-ext4 backed tmp seems to work too. So it may depend on Filesystem Futures (the ext4 i've used had been mkfs'ed with "-o dir_index, extent", or the fact that i'd symlinked the /mnt/blobfusetmp to the folder on mentioned ext4-lvm. If necessary i can provide some steps to reproduce it.

**Comment by vibhansa-msft** [comment] 2020-09-29 07:11
@anisoptera does this problem still persist ? if so can you provide exact steps to recreate it.

**Comment by hphuhtin** [comment] 2020-10-01 12:45
Not sure if this is related - I get the 0 byte files if I enable Immutable blob storage access policy on the container on the Azure side. Otherwise, with tmp-path on ext4 just "/dev/sdb on /logs type ext4 (rw,relatime,data=ordered)" it seems to work ok.

**Comment by vibhansa-msft** [comment] 2020-10-07 09:47
Immutable blob storage is not supported by blobfuse as of now. By default blobfuse first creates an empty file on the container and then uploads the data to it. So in case of immutable storage you will only see 0 byte files for any new file that gets created in mounted path. However to get around this issue, you can always have the file created in some other location and then copy the file to mounted path. As for other cases its working fine, I am closing this issue.

**Closed by vibhansa-msft** 2020-10-07 09:47 UTC
Labels: bug, investigation needed, triaged
