### ISSUE TITLE
blobfuse2 mount all fails without config file.

### ISSUE THREAD

**Issue by ruben-dedoncker** [Azure/azure-storage-fuse#938] opened 2022-10-13 12:28 UTC
### Which version of the blobfuse was used?
blobfuse2 version 2.0.0-preview.3

### Which OS (please include version) are you using?
Ubuntu 20.04 (WSL2)

### What problem was encountered?
Running the `blobfuse2 mount all` command with the `AZURE_STORAGE_ACCOUNT` and `AZURE_STORAGE_ACCESS_KEY` environment variables set still fails since it expects a config file.

The error is as follows
`invalid config file [Config File "config" Not Found in "[]"]`

### Have you found a mitigation/solution?
No

### If relevant, please share your mount command.
`blobfuse2 mount ~/blobmount --tmp-path=/mnt/blobfusetmp`

**Comment by gapra-msft** [comment] 2022-10-13 15:10
Hi @ruben-dedoncker, thank you for reporting this issue. I was able to reproduce this issue. We will investigate and get back to you as soon as we can.

**Comment by gapra-msft** [comment] 2022-10-13 15:23
It looks like this is a bug with the code where we read in the configuration file. I have started a PR here https://github.com/Azure/azure-storage-fuse/pull/939 which should resolve the issue you are experiencing.

Thank you again for reporting this issue

**Comment by gapra-msft** [comment] 2022-10-19 03:08
Resolved in main https://github.com/Azure/azure-storage-fuse/pull/939

**Comment by gapra-msft** [comment] 2022-10-19 03:10
@ruben-dedoncker I will close this issue since a fix has been merged into main. Please feel free to build off the main branch and try out the code while we prepare for our next release. I am also happy to provide a binary if that is more convenient for you.

In case you experience this issue again or the PR didnt solve your problem, please reopen this issue and we will investigate further.

**Closed by gapra-msft** 2022-10-19 03:10 UTC
Labels: bug, fixed in dev, V2
