### ISSUE TITLE
[docs] Need performance test report for blobfuse V2

### ISSUE THREAD

**Issue by cvvz** [Azure/azure-storage-fuse#901] opened 2022-09-13 09:13 UTC
Blobfuse V2 must have a lot of improvement in performance comparing with V1. We need the performance data to convince our customers to upgrade from V1. Could you please provide a performance test report for blobfuse V2?

**Comment by vibhansa-msft** [comment] 2022-09-13 09:21
Performance results are very much dependent on your Machine/VM and Storage account features along with network and other factors. We have done a performance comparison between v1 and v2, and v2 has outperformed v1 in all aspects. As of now we do not publish these detailed performance reports, as they are dependent on lot of factors. However, here is a summary of our preview3 performance analysis done by running v1 and v2 in a controlled environment:

<html>
<body>


Scenario | Results
-- | --
1 Billion file list | Works in v2, while not supported in v1
1 TB file upload/download | Works in v2, while not supported in v1
FIO Serial read | 14% improvement in v2
git clone of large repository | 26% improvement in v2
ResNet50 processing | 7% improvement in v2
File upload/download | 11% upload, 5% download improvement in v2


</body>
</html>

**Comment by vibhansa-msft** [comment] 2022-09-13 16:02
As of now we do not have any plans to publish such report as for v1 also it was never done. However, when we are close to GA of blobfuse2 we might reconsider this based on customer feedback.
Closing this as it's not a bug. We will add this item to our backlog so that during our GA we can consider it.

**Closed by vibhansa-msft** 2022-09-13 16:02 UTC
Labels: question, V2
